File Management - Unhide UploadInfo interface
DevExpress/devextreme-documentation pull request #1324
Opened 2020-10-01 10:26 UTC by Staziz

2020-10-01 19:19 UTC, vladkovl approved these changes

2020-10-02 08:58 UTC, AnnaKondratova approved these changes

2020-10-06 08:25 UTC, RomanTsukanov requested changes

2020-10-06 08:25 UTC, RomanTsukanov commented on concepts/Common/Modularity/02 DevExtreme Modules Structure/file_management/upload_info.md
> +Exposes the Upload Info.
```suggestion
Exposes an object that provides information about the file upload session.
```

2020-10-06 08:25 UTC, RomanTsukanov commented on concepts/Common/Modularity/02 DevExtreme Modules Structure/file_management/upload_info.md
> +- *default* - The [Upload Info](/api-reference/50%20Common/Object%20Structures/UploadInfo '/Documentation/ApiReference/Common/Object_Structures/UploadInfo/')
```suggestion
- *default* - The [UploadInfo](/api-reference/50%20Common/Object%20Structures/UploadInfo '/Documentation/ApiReference/Common/Object_Structures/UploadInfo/') object
```

2020-10-06 08:35 UTC, RomanTsukanov approved these changes

2020-10-06 08:36 UTC, AnnaKondratova approved these changes

2020-10-06 08:39 UTC, merged