Convert VectorMap and RangeSelector topics to md
DevExpress/devextreme-documentation pull request #1645
Opened 2020-12-28 12:05 UTC by AlexJameson

2020-12-28 12:48 UTC, RomanTsukanov requested changes

2020-12-28 12:48 UTC, RomanTsukanov commented on concepts/05 Widgets/VectorMap/40 End-User Interaction/End-User Interaction.md
> +- Hovering
Let's reorder the items as the articles and add links to the articles.

2020-12-29 08:36 UTC, RomanTsukanov commented on concepts/05 Widgets/VectorMap/40 End-User Interaction/End-User Interaction.md
> +- [Elements selection](/Documentation/Guide/Widgets/VectorMap/End-User_Interaction/#Selection)
```suggestion
- [Element selection](/Documentation/Guide/Widgets/VectorMap/End-User_Interaction/#Selection)
```

2020-12-29 08:58 UTC, RomanTsukanov approved these changes

2020-12-29 09:14 UTC, dirk-pieterse approved these changes

2020-12-29 09:14 UTC, dirk-pieterse commented on concepts/05 Widgets/RangeSelector/10 Visual Elements/Visual Elements.md
> +The image below displays the **RangeSelector** element map. **Hover** over the image and to see the **RangeSelector** element names. Click an element to navigate to a topic with more details.
```suggestion
The image below displays the **RangeSelector** element map. **Hover** over the image to show the **RangeSelector** element names. Click an element to navigate to a topic with more information.
```

2020-12-29 09:14 UTC, dirk-pieterse commented on concepts/05 Widgets/VectorMap/40 End-User Interaction/End-User Interaction.md
> +This section contains guides on the following end-user interaction features:
```suggestion
This section contains guides on the following user interaction features:
```

2020-12-29 09:17 UTC, merged