20_2 Scheduler scrollTo: create description
DevExpress/devextreme-documentation pull request #1687
Opened 2021-01-13 15:11 UTC by pavel-2020

[Trello card](https://trello.com/c/MFxkhwH8/1584-describe-dxscheduler-scrolltodategroupallday)

2021-01-14 10:01 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +Scrolls the current view to a specified date, time, and optionally, appointment group. Requires the [height](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#height) property to be s
> to a specified date, time, and optionally, appointment group

There's also an all-day panel, so I would not list all the elements. Also, let's specify the exception of the Agenda view here instead of the full description.

```suggestion
Scrolls the current view to a specified position. Available for all views except *"agenda"*. Requires the [height](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#height) property to be set.
```

2021-01-14 10:01 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +A date and time.
```suggestion
A date and time to scroll to.
```

2021-01-14 10:01 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +Specifies the appointment group if any.
```suggestion
An appointment group (optional).
```

2021-01-14 10:01 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +If **true**, scrolls to the top of the view. Appliable for the *"day"* and *"week"* [views](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/views/) if [showAllDayPanel](/Documentatio
> Appliable for the *"day"* and *"week"* [views](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/views/) if [showAllDayPanel](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#showAllDayPanel) is enabled.

Applies to workweek view as well. Anyway, it's a bit hard to keep all these prerequisites in mind. Let's just say as following:

```suggestion
If **true**, scrolls the view to the all-day panel. Applies only if the all-day panel is [visible](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#showAllDayPanel).
```

2021-01-14 10:01 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +This method is available for all views except *"agenda"*.
Moved to the short description.

```suggestion

```

2021-01-15 14:23 UTC, RomanTsukanov requested changes

2021-01-15 14:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/1 Configuration/currentView.md
> +
scrollTo has a very narrow pool of use-cases, there's no reason to mention it in this article. You can add a link to the See Also section in the scrolling description: https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/scrolling/

2021-01-15 14:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +- [endDayHour](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#endDayHour)
How are these properties connected with the method? Let's give links to the scrolling object and the crossScrollingEnabled property instead.

2021-01-18 09:06 UTC, RomanTsukanov requested changes

2021-01-18 09:06 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/1 Configuration/scrolling.md
> +- [scrollTo(date, group, allDay)](/Documentation/ApiReference/UI_Widgets/dxScheduler/Methods/#scrollTodate_group_allDay)
```suggestion
#####See Also#####
- [scrollTo(date, group, allDay)](/Documentation/ApiReference/UI_Widgets/dxScheduler/Methods/#scrollTodate_group_allDay)
```

2021-01-18 09:06 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +If **true**, scrolls to the all-day panel of the specified group. Applies only if the all-day panel is [visible](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#showAllDayPanel).
```suggestion
If **true**, scrolls the view to the all-day panel of the specified group. Applies only if the all-day panel is [visible](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#showAllDayPanel).
```

2021-01-18 11:05 UTC, AryamnovEugeniy approved these changes

2021-01-18 11:56 UTC, dirk-pieterse approved these changes

2021-01-18 11:56 UTC, dirk-pieterse commented on api-reference/10 UI Widgets/dxScheduler/1 Configuration/scrolling.md
> +Scrolling allows a user to browse data left outside the current viewport. The UI component contains two scrolling modes detailed in the [mode](/Documentation/ApiReference/UI_Widgets/dxScheduler/Confi
```suggestion
Scrolling allows a user to browse data outside the current viewport. Information about the two scrolling modes is available in the [mode](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/scrolling/#mode) option description.
```

2021-01-18 11:56 UTC, dirk-pieterse commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +Scrolls the current view to a specified position. Available for all views except *"agenda"*. Requires the [height](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#height) property t
```suggestion
Scrolls the current view to a specified position. Available for all views except *"agenda"*. You should specify the [height](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#height) property to use this option.
```

2021-01-18 11:56 UTC, dirk-pieterse commented on api-reference/10 UI Widgets/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
> +[note] If you need to navigate to a date outside of the current view, use the [currentDate](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#currentDate) property instead.
```suggestion
[note] If you need to navigate to a date outside the current view, use the [currentDate](/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#currentDate) property instead. 
```

2021-01-18 12:09 UTC, AryamnovEugeniy approved these changes

2021-01-18 15:15 UTC, RomanTsukanov approved these changes

2021-01-19 10:30 UTC, RomanTsukanov approved these changes

2021-01-19 10:51 UTC, merged