20_1 GridBaseColumn\lookup\dataSource: fix link for DataSource configuration object (T966415)
DevExpress/devextreme-documentation pull request #1740
Opened 2021-01-21 13:21 UTC by pavel-2020

[Trello card](https://trello.com/c/itmnM6zy/1604-t966415-documentation-the-lookupdatasource-topic-contains-wrong-information)
Since it is GridBaseColumn, a link for DataGrid has been used.

2021-01-21 13:29 UTC, RomanTsukanov requested changes

2021-01-21 13:29 UTC, RomanTsukanov commented on api-reference/_hidden/GridBaseColumn/lookup/dataSource.md
> +- [**DataSource configuration object**](/Documentation/Guide/Widgets/DataGrid/How_To/Bind_a_Lookup_Column_to_a_Custom_Data_Source/)
This link is unexpected under the caption DataSource configuration object. Yes. it doesn't explain how to use the object, we don't want to confuse our readers. Let's keep the old link here, but change the description a bit:

> A **DataSource** configuration object. You can find a code example for this use case in the following help topic: [Bind a Lookup Column to a Custom Data Source](). For more information about the **DataSource** and DevExtreme Data Layer, refer to the [Data Layer](/concepts/70%20Data%20Binding/5%20Data%20Layer '/Documentation/Guide/Data_Binding/Data_Layer/') article.

2021-01-21 14:19 UTC, RomanTsukanov requested changes

2021-01-21 14:19 UTC, RomanTsukanov commented on api-reference/_hidden/GridBaseColumn/lookup/dataSource.md
> +A **DataSource** configuration object. You can find a code example for this use case in the following help topic: [Bind a Lookup Column to a Custom Data Source](/Documentation/Guide/Widgets/DataGrid/
> /Documentation/Guide/**Widgets**/DataGrid/How_To/Bind_a_Lookup_Column_to_a_Custom_Data_Source/

The link is outdated

2021-01-21 15:40 UTC, RomanTsukanov approved these changes

2021-01-22 08:34 UTC, dirk-pieterse approved these changes

2021-01-22 08:34 UTC, dirk-pieterse commented on api-reference/_hidden/GridBaseColumn/lookup/dataSource.md
> +A **DataSource** configuration object. You can find a code example for this use case in the following help topic: [Bind a Lookup Column to a Custom Data Source](/Documentation/Guide/UI_Components/{Wi
```suggestion
A **DataSource** configuration object. You can find code for this example in the following help topic: [Bind a Lookup Column to a Custom Data Source](/Documentation/Guide/UI_Components/{WidgetName}/How_To/Bind_a_Lookup_Column_to_a_Custom_Data_Source/). For more information about the **DataSource** and DevExtreme Data Layer, refer to the [Data Layer](/concepts/70%20Data%20Binding/5%20Data%20Layer '/Documentation/Guide/Data_Binding/Data_Layer/') article.
```

2021-01-22 09:51 UTC, merged