Fix DocIssues: Form - Item Options
DevExpress/devextreme-documentation pull request #1746
Opened 2021-01-21 16:54 UTC by AlexJameson

2021-01-22 16:21 UTC, RomanTsukanov requested changes

2021-01-22 16:21 UTC, RomanTsukanov commented on concepts/05 UI Components/Form/20 Change Options at Runtime/10 Item Options.md
> +#include form-item-options
This note breaks the connection between the text and the code sample. Let's move it to the end of the article.

2021-01-25 12:13 UTC, RomanTsukanov approved these changes

2021-01-25 17:20 UTC, arminal reviewed
I couldn't edit these sentences in the program, so I am leaving a note here. Can you rewrite these 2? "being called" and "with ***".
Being called with the field* parameter only, this method returns the current configuration of the specified form item.
With Angular, Vue, or React, bind the property that should be changed to a component property.

2021-01-25 17:20 UTC, arminal commented on includes/form-item-options.md
> +When you modify an item, the Form also refreshes all other items in its group. If an item is not in a group, the whole Form is refreshed. To update only the items of your choice, wrap them into a sep
```suggestion
When you modify an item, the Form also refreshes all other items in its group. If an item is not in a group, the whole Form is refreshed. To update only your chosen items, wrap them into a separate group.
```

2021-01-27 10:15 UTC, merged