20_1 DataGrid calculateCustomSummary: docissues
DevExpress/devextreme-documentation pull request #1816
Opened 2021-02-04 12:30 UTC by pavel-2020

[Trello](https://trello.com/c/gvA1YKgd/1586-docissues-datagrid-summarycalculatecustomsummary)

2021-02-04 13:31 UTC, RomanTsukanov requested changes

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +If the **totalItems**.[column](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/summary/totalItems/#column) property is set, this field contains the value from this column. If **tot
As I see, the information was already there, yet readers still don't notice it. Let's change the description more drastically then:

```suggestion
A column value used in calculation. If you need an entire data object in this field, do not specify the summary item's [column](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/summary/totalItems/#column) property.
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> -                                break;
I vote for keeping the break. Sure, the code works without it, but it's good to show it just in case somebody wants to add a default case.

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +**calculateCustomSummary** is called before [calculateCellValue](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/columns/#calculateCellValue). If you want to create a new column an
- You give some facts, which I'm sure are true, but the use case isn't clear to me. The first sentence in a paragraph should present the main thought of this paragraph. So what's this thought?
- Elaborate on what is happening in the code sample.

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +    const  calculateArea = (rowData) => {
```suggestion
    const calculateArea = (rowData) => {
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +    const  calculateArea = (rowData) => {
Why is this an arrow function, but calculateAreaSummary below is declared as a regular function?

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +        if (options.name === "calculateAreaSummary") {
```suggestion
        if (options.name === "AreaSummary") {
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +                    options.totalValue += calculateArea(options.value);
```suggestion
                options.totalValue += calculateArea(options.value);
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +                ],
```suggestion
                    name: "AreaSummary",
                    summaryType: "custom"
                    showInColumn: "Area",
                    displayFormat: "Total Area: {0}",
                }],
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +    <!--TypeScript-->
Use an updated template for code samples, the one where code is split across tabs named like files in a real project.

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +        constructor(private service: Service) {
```suggestion
        constructor() {
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +            Dx{WidgetName}Module
Don't use placeholders if the description is not inherited.

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +        ></dxi-column>
```suggestion
            [calculateCellValue]="calculateArea">
        </dxi-column>
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +            >
```suggestion
                displayFormat="Total Area: {0}">
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +
```suggestion
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +        if (options.name === "calculateAreaSummary") {
Same mistake in samples for other platforms.

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +    };
```suggestion
    }
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +            <DataGrid ...>
```suggestion
            <DataGrid ... >
```

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +Note that the example above uses totalItems.**showInColumn** instead of totalItems.**column**. This is because **calculateCustomSummary** works with values from multiple columns.
The effect and the cause are switched places. We need entire data objects within calculateCustomSummary. To achieve that, we don't specify the column. Not the other way around. Give this information above the example.

2021-02-04 13:31 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
>  ---
Add Vue and React versions.

2021-02-09 10:06 UTC, RomanTsukanov requested changes

2021-02-09 10:06 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +            },
```suggestion
```

2021-02-09 10:06 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +                if (options.component.isRowSelected(options.value.ID)) {
`if (options.summaryProcess === "calculate") {` is missing

2021-02-09 10:24 UTC, RomanTsukanov approved these changes

2021-02-10 07:56 UTC, dirk-pieterse approved these changes

2021-02-10 07:56 UTC, dirk-pieterse commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +A column value used in calculation. If you need an entire data object in this field, do not specify the summary item's [column](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/summ
"in calculation" In which calculation?

2021-02-10 07:56 UTC, dirk-pieterse commented on api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
> +You can use the **value** field to access a column value. If you do not specify a [column](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/summary/totalItems/#column) by which to c
- What do you mean when you say "to access"? To get the value? To retrieve the value?
- "by which to calculate the summary" Do you mean 'used to calculate the summary' or 'for which to calculate the summary'?

2021-02-11 07:36 UTC, merged