Describe the shift visualRangeUpdateMode for the chart valueAxis
DevExpress/devextreme-documentation pull request #206
Opened 2020-01-29 14:52 UTC by AlexJameson

2020-01-29 15:09 UTC, RomanTsukanov requested changes

2020-01-29 15:09 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/valueAxis/visualRangeUpdateMode.md
> +- *"Shift"*
```suggestion
- *"shift"*     
```

2020-01-29 15:09 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/valueAxis/visualRangeUpdateMode.md
>      - if *"keep"*, then *"keep"*.
This means that the value axis' mode is the same as the argument axis' mode. These ifs are unnecessary.

2020-01-30 08:09 UTC, alexanderPolosatov approved these changes
LGTM

2020-01-30 08:29 UTC, RomanTsukanov approved these changes

2020-01-30 09:23 UTC, dirk-pieterse approved these changes

2020-01-30 09:23 UTC, dirk-pieterse commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/valueAxis/visualRangeUpdateMode.md
> +The same as the *"auto"* mode.
```suggestion
The same as *"auto"* mode.
```

2020-01-30 09:28 UTC, merged