Prepare Getting Started with Popup Guide
DevExpress/devextreme-documentation pull request #2137
Opened 2021-04-07 15:47 UTC by czernous-devexpress

2021-04-08 09:05 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxPopup/dxPopup.md
>  #include common-readguidesbutton with {
Replace with the Start Tutorial button.

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +    var popupText = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```suggestion
    const popupText = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +---
Rename the article to Show and Hide the Popup

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/00 Getting Started with Popup.md
> +The **Popup** displays content in a window that overlays the current view.
```suggestion
The Popup displays content in a window that overlays the current view.
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/00 Getting Started with Popup.md
> +This tutorial explains how to add a **Popup** to a page, define its content, and configure its core features. The following control demonstrates the result:
```suggestion
This tutorial explains how to add a Popup to a page, define its content, and configure its core features. The following control demonstrates the result:
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +Use the **visibility** parameter to control whether the popup is hidden or shown by default. With this parameter set to **true**, the popup will displayed by default and cannot be reopened once close
- "by default" - not recommended.
- "With this parameter set to **true**, the popup will displayed by default" - this repeats part of the thought from the previous sentence.
- "Add a [button](/Documentation/ApiReference/UI_Components/dxButton/) and implement popup toggle in its **onClick** handler." - this shouldn't be a direct instruction. The show and hide methods can be called in many other ways, so we can only describe how we call them.
- "close the popup on outside clicks" - sounds strange, although I do understand what it says.

```suggestion
To show the Popup, call its [show()](/Documentation/ApiReference/UI_Components/dxPopup/Methods/#show) method. In the code below, this method is called when users click the Open Popup button. You can also enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property to show the Popup immediately after creation.

To hide the Popup, call its [hide()](/Documentation/ApiReference/UI_Components/dxPopup/Methods/#hide) method. Users can hide the Popup when they click outside its boundaries. To enable this functionality, set the [closeOnOutsideClick](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#closeOnOutsideClick) property to **true**.
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +Use the **visibile** parameter to control whether the popup is hidden or shown by default. With this parameter set to **true**, the popup will displayed by default and cannot be reopened once closed.
Try to rewrite this paragraph in the manner of the suggestion above.

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +    >
```suggestion
        (onClick)="togglePopup()">
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +    >
```suggestion
        [closeOnOutsideClick]="true">
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +        </div>
```suggestion
        <!-- ... -->
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +            >
```suggestion
                :close-on-outside-click="true">
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +                </template>
```suggestion
                <!-- ... -->
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +        const [isPopupVisible, setPopupVisivility] = useState(true);
visivility

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +                >
```suggestion
                    onHiding={togglePopup}>
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Set Visibility.md
> +                    // ...
The Popup should use a contentRender, so there shouldn't be omitted nested elements.

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +Set the [showTitle](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle) property to **true** to display popup's title and use the [title](/Documentation/ApiReference/UI_Compon
```suggestion
Set the [showTitle](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle) property to **true** to display popup's title bar and use the [title](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#title) property to define its text: 
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +    // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +    // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +        </div>
```suggestion
        title="Information">
        <!-- ... -->
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +            // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +                </template>
```suggestion
                title="Information">
                <!-- ... -->
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +    }
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +
```suggestion
    // ...
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +                // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +                </Popup>
```suggestion
                    title="Information"              
                />
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +Use [hight](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set popup's size
```suggestion
Use the [height](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set popup's size:
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +Use [hight](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set popup's size
Rename the article to Resize the Popup

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +    // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +    // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +        </div>
```suggestion
        [width]="500">
        <!-- ... -->
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +            // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +                </template>
```suggestion
                :width="500">
                <!-- ... -->            
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +    }
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +
```suggestion
    // ...
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +                </Popup>
```suggestion
                />
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +                // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +Users can scroll popup's content. To enable this functionality, configure the [scrollView](/Documentation/Guide/UI_Components/ScrollView/Overview/) and set its **height** and **width**.
```suggestion
Users can scroll popup's content. To enable this functionality, wrap the content into the [ScrollView](/Documentation/Guide/UI_Components/ScrollView/Overview/) component and set its **height** and **width** to be 100% of the popup content area:
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                const content = $("<div />");
You need to show full content template to illustrate this case properly.

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +        // ...
```suggestion
            // ...
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +    // ...
```suggestion
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +---
Let's add information about the resizeEnabled property.

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Configure User Interaction.md
> +Users can drag the popup. To configure this functionalty, use the [dragEnabled](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#dragEnabled) property.
The descriptions follow the same pattern over and over again, it seems robotic. Let's change it a bit:

```suggestion
The Popup supports drag and drop. To enable this functionalty, set the [dragEnabled](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#dragEnabled) property to **true**. Users drag the Popup by its title bar, so make sure that you [configured it]().
```

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Configure User Interaction.md
> +    url: "https://js.devexpress.com/Demos/WidgetsGallery/Demo/Popup"
Dragging is not enabled in this demo. Why is this link given here?

2021-04-08 09:05 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Configure User Interaction.md
> +}
Let's add information about the position property and rename the article to Position the Popup.

2021-04-12 10:15 UTC, RomanTsukanov requested changes

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is two-way bound to a variabl
```suggestion
To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is two-way bound to a variable. The `togglePopup()` method toggles the value between **true** and **false** when users click the Open Popup button.
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is two-way bound to a variabl
```suggestion
To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is two-way bound to a variable. The `togglePopup()` method toggles the value between **true** and **false** when users click the Open Popup button.
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is bound to a state variable
```suggestion
To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is bound to a state variable with the React <a href="https://reactjs.org/docs/hooks-state.html" target="_blank">useState</a> hook. The `togglePopup` function toggles the value between **true** and **false** when users click the Open Popup button.
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +You can define static content in the Popup's markup or use the [contentTemplate](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#contentTemplate) when the content is dynamic. In the
```suggestion
You can define static content in the Popup's markup or use the [contentTemplate](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#contentTemplate) when the content is dynamic. In the code below, the content is static but we use **contentTemplate** as dynamic content will be added at a later stage.
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +        <div *dxTemplate="let data of 'content'">
```suggestion
    <dx-popup
        contentTemplate="popup-content">
        <div *dxTemplate="let data of 'popup-content'">
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +                <template #content>
```suggestion
            <DxPopup
                content-template="popup-content">
                <template #popup-content>
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +You can define the content directly between the Popup tags like you would with a normal `<div>`:
```suggestion
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +            <>
```suggestion
            <React.Fragment>
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +            </>
```suggestion
            </React.Fragment>
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +Use the [height](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set popup's
A link to `resizeEnabled` is missing.

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                <>
```suggestion
                <React.Fragment>
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                </>
```suggestion
                </React.Fragment>
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                        // ...
```suggestion
                        {/* ... */}
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +            <DxPopup...>
```suggestion
            <DxPopup ... >
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                </template>
```suggestion
                <template #content>
                    <DxScrollView
                        height="100%"
                        width="100%">
                        <!-- ... -->
                    </DxScrollView>
                </template>            
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +To position the Popup within the viewport, use the [position](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#position) property. The Popup supports drag and drop. To enable this fun
```suggestion
To position the Popup within the viewport, use the [position](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#position) property. The Popup also allows users to change its position via drag and drop. To enable this functionalty, set the [dragEnabled](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#dragEnabled) property to **true**. Users drag the Popup by its title bar, so make sure that you [configured it](Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle).
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +To position the Popup within the viewport, use the [position](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#position) property. The Popup supports drag and drop. To enable this fun
> [configured it](Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle)

Better refer to the Define the Title topic.

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +
```suggestion
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +    }
```suggestion
    // ...
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
> +                    contentRender={renderContent}/>
```suggestion
                <Popup
                    contentRender={renderContent}
                />
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +    // ...
```suggestion
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +                @click="togglePopup"/>
```suggestion
                @click="togglePopup"
            />
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +    // ...
```suggestion
    // ...
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +                    onHiding={togglePopup}/>
```suggestion
                    onHiding={togglePopup}
                />
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +                    onClick={togglePopup}/>
```suggestion
                    onClick={togglePopup}
                />
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +                // ...
```suggestion
                    title="Information"
                />
                {/* ... */}
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +                // ...
```suggestion
                    resizeEnabled={true}
                />
                {/* ... */}
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +
```suggestion
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +    <dx-popup...>
```suggestion
    <dx-popup ... >
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                <!--...-->
```suggestion
                <!-- ... -->
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +        const renderContent = () => {
This function has 4 extra spaces from the left.

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +                    height={500}/>
```suggestion
                    contentRender={renderContent}
                />
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +    // ...
```suggestion

```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +        </div>
```suggestion
        <!--...-->
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +
```suggestion
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +            // ...
```suggestion
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +                </template>
```suggestion
                <!-- ... -->
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +                // ...
```suggestion
                    position="center"
                />
                {/* ... */}
```

2021-04-12 10:15 UTC, RomanTsukanov commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Set the Size.md
> +Use the [height](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set popup's
Rename the article to Resize the Popup.

2021-04-14 07:54 UTC, RomanTsukanov approved these changes

2021-04-14 16:12 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To hide the Popup, call its [hide()](/Documentation/ApiReference/UI_Components/dxPopup/Methods/#hide) method. Users can hide the Popup when they click outside its boundaries. To enable this functiona
```suggestion
Call the Popup's [hide()](/Documentation/ApiReference/UI_Components/dxPopup/Methods/#hide) method to hide the Popup. Users can also hide the Popup when they click outside its boundaries. To enable this functionality, set the [closeOnOutsideClick](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#closeOnOutsideClick) property to **true**.
```

2021-04-14 16:16 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is two-way bound to a variabl
```suggestion
Enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property to show the Popup. In the code below, the value of this property is two-way bound to a variable. The `togglePopup()` method toggles the value between **true** and **false** when users click the Open Popup button.
```

2021-04-14 16:46 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is two-way bound to a variabl
```suggestion
Enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property to show the Popup. In the code below, the value of this property is two-way bound to a variable. The `togglePopup()` method toggles the value between **true** and **false** when users click the Open Popup button.
```

2021-04-14 16:48 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To show the Popup, enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property. In the code below, the value of this property is bound to a state variable
```suggestion
Enable the [visible](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#visible) property to show the Popup. In the code below, the value of this property is bound to a state variable with the React <a href="https://reactjs.org/docs/hooks-state.html" target="_blank">useState</a> hook. The `togglePopup` function toggles the value between **true** and **false** when users click the Open Popup button.
```

2021-04-14 16:50 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
> +To hide the Popup, call the togglePopup function when the [onHiding](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#onHiding) event fires. Users can hide the Popup when they click o
```suggestion
Call the togglePopup function when the [onHiding](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#onHiding) event fires to hide the Popup. Users can also hide the Popup when they click outside its boundaries. To enable this functionality, set the [closeOnOutsideClick](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#closeOnOutsideClick) property to **true**.
```

2021-04-14 16:53 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/05 Define the Title.md
> +Set the [showTitle](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle) property to **true** to display popup's title bar and use the [title](/Documentation/ApiReference/UI_Co
```suggestion
Set the [showTitle](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle) property to **true** to display the Popup's title bar and use the [title](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#title) property to define its text: 
```

2021-04-14 16:54 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
> +Use the [height](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set popup's
```suggestion
Use the [height](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#height) and [width](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#width) properties to set the Popup's size. Set the [resizeEnabled] property to **true** to allow users resize the Popup.
```

2021-04-14 17:02 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/07 Add Scrolling.md
> +Users can scroll popup's content. To enable this functionality, wrap the content into the [ScrollView](/Documentation/Guide/UI_Components/ScrollView/Overview/) component and set its **height** and **
```suggestion
Users can scroll the Popup's content. To enable this functionality, wrap the content into the [ScrollView](/Documentation/Guide/UI_Components/ScrollView/Overview/) component and set its **height** and **width** to 100% of the Popup content area:
```

2021-04-14 17:06 UTC, albertov05 commented on concepts/05 UI Components/Popup/00 Getting Started with Popup/08 Position the Popup.md
> +To position the Popup within the viewport, use the [position](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#position) property. The Popup also allows users to change its position v
```suggestion
Use the [position](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#position) property to position the Popup within the viewport. Users can also drag and drop the Popup to change its position. To enable this functionalty, set the [dragEnabled](/Documentation/ApiReference/UI_Components/dxPopup/Configuration/#dragEnabled) property to **true**. Users drag the Popup by its title bar, so make sure that you [configure it](Documentation/ApiReference/UI_Components/dxPopup/Configuration/#showTitle).
```

2021-04-15 08:25 UTC, merged