Fix Imports in Documentation
DevExpress/devextreme-documentation pull request #2609
Opened 2021-07-20 15:48 UTC by AlexJameson

2021-07-20 16:05 UTC, nightskylark requested changes

2021-07-20 16:05 UTC, nightskylark commented on api-reference/50 Common/utils/utils/getTimeZones(date).md
> +    import { timeZoneUtils } from 'devextreme/time_zone_utils';
The import is named as `getTimeZones`, not `timeZoneUtils`
https://github.com/DevExpress/DevExtreme/blob/21_2/js/time_zone_utils.js#L4

2021-07-21 07:43 UTC, RomanTsukanov commented on concepts/05 UI Components/Diagram/30 Diagram Tools.md
>        onCustomCommand(e) {
The function should be declared inside a class. I think we need to show the full code.

2021-07-22 07:27 UTC, RomanTsukanov approved these changes

2021-07-22 08:59 UTC, merged