Grids toolbar: add description
DevExpress/devextreme-documentation pull request #2626
Opened 2021-07-26 08:35 UTC by pavel-2020

2021-07-27 10:28 UTC, RomanTsukanov requested changes

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +Customizes toolbar.
```suggestion
Configures the toolbar.
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +    url: "https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/UICustomization/"
Is there gonna be a new demo targeting the TreeList specifically?

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +**Predefined Items**
```suggestion
## Predefined Controls
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +Predefined items include:
```suggestion
Predefined controls appear on the toolbar depending on whether a specific DataGrid feature is enabled. The following table illustrates the dependency:
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +    <th>Prerequisites</th>
Let's reorder the table columns:

```suggestion
    <th>Control Name</th>
    <th>Image</th>
    <th>Prerequisites</th>
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +    <td>editing.<a href="/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#allowAdding">allowAdding</a> is set to <b>true</b></td>
Let's add full links. Make `editing` a link too.

```suggestion
    <td>editing.<a href="/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#allowAdding">allowAdding</a> is <b>true</b></td>
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +To add a predefined item, add its string to the toolbar array. If you need to configure an item, add an object instead and specify the [name](/Documentation/ApiReference/UI_Components/dxTreeList/Conf
```suggestion
If you need to customize a predefined item, add an object to the **items[]** array. This object must contain the item's [name]({currentpath}/#name) and [properties]() that you want to customize. If an item does not need customization, simply include its name in the **items[]** array.

[important] The TreeList does not display controls missing from the **items[]** array. Ensure that this array includes controls for all enabled features.
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +**Custom Items**
```suggestion
## Custom Controls
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
> +[note] If you use toolbar to specify a custom item and/or configure a predefined item, add corresponding strings for other used features. Otherwise, the TreeList will not display these controls.
Make the descriptions based on the [Toolbar Customization](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ToolbarCustomization/jQuery/Light/) demo.

```suggestion
- DevExtreme components
...

- Custom elements
...
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/_hidden/dxTreeListToolbar/items.md
> +Configures toolbar items' settings.
```suggestion
Configures toolbar items.
```

2021-07-27 10:28 UTC, RomanTsukanov commented on api-reference/_hidden/dxTreeListToolbarItem/name.md
> +Specifies the toolbar item's name.
```suggestion
A name used to identify the toolbar item.
```

2021-08-25 14:04 UTC, RomanTsukanov requested changes

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +If you need to customize a predefined item, add an object to the **toolbar**.[items[]](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/) array. This object must c
```suggestion
If you need to customize a predefined item, add an object to the **items[]** array. This object must contain the item's [name](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/#name) and [properties](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/) that you want to customize. If an item does not need customization, simply include its name in the **toolbar**.**items[]** array.
```

2021-08-25 14:04 UTC, RomanTsukanov commented on api-reference/_hidden/dxDataGridToolbar/dxDataGridToolbar.md
> +![DevExtreme DataGrid - Toolbar](/images/DataGrid/toolbar.png)
Move the image before the demo link.

2021-08-25 14:04 UTC, RomanTsukanov commented on api-reference/_hidden/dxDataGridToolbarItem/dxDataGridToolbarItem.md
> +      <td> <a href='https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/groupPanel/'>groupPanel</a>.<a href='https://js.devexpress.com/Documentation/ApiReferen
```suggestion
      <td> <a href='https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/groupPanel/'>groupPanel</a>.<a href='https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/columnChooser/#enabled'>visible</a> is set to <b>true</b> or <i>\"auto\"</i></td>
```

2021-08-25 14:04 UTC, RomanTsukanov commented on api-reference/_hidden/dxTreeListToolbar/dxTreeListToolbar.md
> +![DevExtreme TreeList - Toolbar](/images/treelist/toolbar.png)
Move the image before the demo link.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +Predefined controls include:
```suggestion
## Predefined Controls

Predefined controls appear on the toolbar depending on whether a specific {WidgetName} feature is enabled. The following table illustrates the dependency:
```

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +    <td><a href="https://js.devexpress.com/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/editing/">editing</a>.<a href="https://js.devexpress.com/Documentation/ApiReference/UI
Use {basewidgetpath} to make links shorter.

> is set to

Just "is" would be enough.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +    <td>filterRow.<a href="https://js.devexpress.com/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/filterRow/#visible">visible</a> is set to <b>true</b> and filterRow.<a href=
Make `filterRow` a link.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +    <td>columnChooser.<a href="https://js.devexpress.com/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/columnChooser/#enabled">enabled</a> is set to <b>true</b></td>
Make `columnChooser` a link.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +    <td>searchPanel.<a href="https://js.devexpress.com/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/searchPanel/#visible">visible</a> is set to <b>true</b></td>
Make `searchPanel` a link.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +##### DevExtreme Components
Don't skip header levels. The previous header level is h1, so this one should be h2.

```suggestion
## DevExtreme Components
```

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +##### Custom Controls
```suggestion
## Custom Controls
```

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +
Let's give a code example.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +Add an object to the **toolbar**.[items[]](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/) array, specify one of the available [widgets](/Documentation/ApiRefer
```suggestion
You can use DevExtreme components as toolbar items. Set the [widget]({currentpath}/#widget) property to specify the component that you want to use and configure the component's [options]({currentpath}/#options).
```

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +
Let's give a code example.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +Add an object to the **toolbar**.[items[]](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/) array, specify the [template](/Documentation/ApiReference/UI_Componen
There's no need to overcomplicate things.

```suggestion
To use a custom control, specify a [template](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/#template) for it.
```

2021-08-25 14:04 UTC, RomanTsukanov commented on api-reference/_hidden/dxDataGridToolbarItem/dxDataGridToolbarItem.md
> +      <td><img src='/images/DataGrid/icons/toolbar_groupPanel.png' alt='DevExtreme JavaScript jQuery Angular UI component DataGrid Toolbar GroupPanel' style='margin:1px; vertical-align:middle'/></td>
The illustration is too wide. Make a screenshot that shows a couple of headers on the group panel.

2021-08-25 14:04 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +    <td><img src="/images/DataGrid/icons/toolbar_searchPanel.png" alt="DevExtreme JavaScript jQuery Angular UI component {WidgetName} Toolbar searchPanel" style="margin:1px; vertical-align:middle"/><
The search panel lacks space. Let's make it a bit wider and match the width with the new group panel illustration.

2021-08-31 11:38 UTC, pavel-2020 commented on api-reference/_hidden/dxDataGridToolbarItem/dxDataGridToolbarItem.md
> +      <td><img src='/images/DataGrid/icons/toolbar_groupPanel.png' alt='DevExtreme JavaScript jQuery Angular UI component DataGrid Toolbar GroupPanel' style='margin:1px; vertical-align:middle'/></td>
![изображение](https://user-images.githubusercontent.com/66619750/131496018-9f8454de-b184-405b-89d5-fbc43babfc3d.png)

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +Predefined controls include:
```suggestion
## Predefined Controls

Predefined controls appear on the toolbar depending on whether a specific DataGrid feature is enabled. The following table illustrates the dependency:
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +		<td><a href="{basewidgetpath}/Configuration/editing/">editing</a>.<a href="{basewidgetpath}/Configuration/editing/#allowAdding">allowAdding</a> is set to <b>true</b></td>
Apply this edit everywhere.

```suggestion
		<td><a href="{basewidgetpath}/Configuration/editing/">editing</a>.<a href="{basewidgetpath}/Configuration/editing/#allowAdding">allowAdding</a> to <b>true</b></td>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +		<td><img src="/images/DataGrid/icons/toolbar_searchPanel.png" alt="DevExtreme JavaScript jQuery Angular UI component {WidgetName} Toolbar searchPanel" style="margin:1px; vertical-align:middle"/></t
Cut the white borders:

![image](https://user-images.githubusercontent.com/18551316/131869781-47054fd9-34ba-42f1-ac5b-e88a4299650a.png)

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +		<!--tab: index.js-->
The examples have 4 extra spaces of indentation.
Don't ever use tab symbol for indents. Configure your text editor to use spaces.

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +If you need to customize a predefined item, add an object to the **items[]** array. This object must contain the item's [name](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/t
Without a commentary, it's unclear what's happening in the example. Let's add it.

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +					}]
The example only covers the case with customization. Add strings to this array.

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +			<dxo-column-chooser [enabled]="true"></dxo-column-chooser
```suggestion
			<dxo-column-chooser [enabled]="true"></dxo-column-chooser>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +				>
```suggestion
					location="after">
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +				<DxColumChooser :enabled="true"/>
```suggestion
				<DxColumnChooser :enabled="true"/>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +						locateInMenu="auto"
```suggestion
						locate-in-menu="auto"
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +		// ...
```suggestion
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +		<dx-data-grid ...>
```suggestion
		<dx-data-grid ... >
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +				<dxi-item location="before">
```suggestion
				<dxi-item>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +					></dx-select-box>
```suggestion
					<dx-select-box>
						<!-- SelectBox properties are specified here -->
					</dx-select-box>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +						/>
```suggestion
						<DxSelectBox>
							<!-- SelectBox properties are specified here -->
						</DxSelectBox>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +					<DxItem location="after">
```suggestion
					<DxItem>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +				dxSelectBox
```suggestion
				DxSelectBox
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +		// ...
```suggestion
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +						<Item location="after">
```suggestion
						<Item>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +							/>
```suggestion
							<SelectBox>
								{/* SelectBox properties are specified here */}
							</SelectBox>
```

2021-09-02 15:30 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +To use a custom control, specify a [template](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/#template) for it.
```suggestion
To use a custom control, specify a [template]({currentpath}/#template) for it.
```

2021-09-03 04:20 UTC, dirk-pieterse approved these changes

2021-09-06 11:32 UTC, RomanTsukanov commented on includes/grids-toolbar.md
> +If you need to customize a predefined item, add an object to the **items[]** array. This object must contain the item's [name](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/t
```suggestion
If you need to customize a predefined control, add an object to the **items[]** array. This object must contain the control's [name](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/#name) and [properties](/Documentation/ApiReference/UI_Components/dx{WidgetName}/Configuration/toolbar/items/) that you want to customize. If a control does not need customization, simply include its name in the **toolbar**.**items[]** array. 
```

2021-09-06 11:43 UTC, RomanTsukanov approved these changes

2021-09-06 13:44 UTC, merged