Gantt: add code snippets to the dependencies option
DevExpress/devextreme-documentation pull request #265
Opened 2020-02-06 09:56 UTC by AnnaKondratova

2020-02-06 11:00 UTC, RomanTsukanov requested changes

2020-02-06 11:00 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxGantt/1 Configuration/dependencies/dataSource.md
> +Refer to the [dependencies]('/Documentation/ApiReference/UI_Widgets/dxGantt/Configuration/dependencies/') option to see how to specify the **dataSource** option.
You shouldn't put links in quotes. The converter won't recognize them.

2020-02-10 07:19 UTC, AnnaKondratova commented on api-reference/10 UI Widgets/dxGantt/1 Configuration/dependencies/dataSource.md
> +Refer to the [dependencies]('/Documentation/ApiReference/UI_Widgets/dxGantt/Configuration/dependencies/') option to see how to specify the **dataSource** option.
Links are updated with the converter.

2020-02-10 14:04 UTC, RomanTsukanov approved these changes

2020-02-11 07:17 UTC, merged