Add the 'null' value type to the CheckBox.value description
DevExpress/devextreme-documentation pull request #2766
Opened 2021-08-27 13:30 UTC by AlexJameson

2021-08-27 15:30 UTC, RomanTsukanov requested changes

2021-08-27 15:30 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
>   value is **true**
```suggestion
 **value** is **true**
```

2021-08-27 15:30 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
>   value is **false**
```suggestion
 **value** is **false**
```

2021-08-27 15:30 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
> + value is **undefined** or **null**
```suggestion
 **value** is **undefined** or **null**
```

2021-08-27 15:30 UTC, RomanTsukanov commented on api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
> +An end-user can use the **Space** key to change the UI component value.
```suggestion
Users can press the Space key to change the **value**.
```

2021-08-30 11:30 UTC, RomanTsukanov approved these changes

2021-08-30 17:12 UTC, albertov05 commented on api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
> +Users can press the Space key to change the **value**.
Can we add bold font to "Space" as well? For example:

`Users can press the **Space** key to change the **value**.`

2021-08-31 06:43 UTC, merged