DataGrid buttons[].disabled: add description
DevExpress/devextreme-documentation pull request #2851
Opened 2021-09-14 05:18 UTC by pavel-2020

[Trello](https://trello.com/c/ynQFdcI6/1848-datagrid-buttonsdisabled-add-description)

2021-09-14 07:33 UTC, RomanTsukanov commented on api-reference/_hidden/dxTreeListColumnButton/disabled.md
> +Use the function to activate or disable the button for specific rows. See a related example in the **buttons[]**.[visible](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/b
Both descriptions are virtually the same. [Use imports for the TreeList](http://tw.devexpress.devx/devextreme-docs-wiki/reuse-content/#imports).

2021-09-16 08:24 UTC, RomanTsukanov requested changes

2021-09-16 08:24 UTC, RomanTsukanov commented on api-reference/_hidden/dxDataGridColumnButton/disabled.md
> +Use the function to activate or disable the button for specific rows. See a related example in the **buttons[]**.[visible](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/columns/b
```suggestion
Use the function to activate or disable the button for specific rows. See a related example in the **buttons[]**.[visible]({currentpath}/#visible) topic.
```

2021-09-16 08:34 UTC, RomanTsukanov approved these changes

2021-09-16 11:05 UTC, dirk-pieterse approved these changes

2021-09-16 11:05 UTC, dirk-pieterse commented on api-reference/_hidden/dxDataGridColumnButton/disabled.md
> +Information about the current row and column that contain the button.
`row and column that contain the button` seems to imply both the column and thr row have a button

2021-09-16 11:52 UTC, merged