TreeView - samples for React and Vue
DevExpress/devextreme-documentation pull request #310
Opened 2020-02-12 12:25 UTC by novsstation

2020-02-13 15:00 UTC, RomanTsukanov requested changes

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +        import { DxTreeView } from 'devextreme-vue/tree-view';
Please move the entire content of the `<script>` to the left.

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +                id: '1',
Move the array contents too.

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +                DxTreeView,
```suggestion
                DxTreeView
```

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +        :items="hierarchicalData" />
```suggestion
            :items="hierarchicalData"
        />
```

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +    <!-- tab: App.js -->import React from 'react';
```suggestion
    <!-- tab: App.js -->
    import React from 'react';
```

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +        import { DxTreeView } from 'devextreme-vue/tree-view';
The TreeView requires the styles. Do not delete the CSS imports.

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +            id: '1',
Same issue with indentation

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/05 Use Hierarchical Data.md
> +            keyExpr='key'
Attributes in the Vue markup should use kebab-case and their values should be in double quotes instead of single ones.

```suggestion
            key-expr="key"
```

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/07 Use Plain Data.md
> +                    dataStructure='plain'
String values in React should use double quotes as well.

```suggestion
                    dataStructure="plain"
```

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/10 Access a Node/05 Within Event Handlers.md
> +                onItemClick(e){
```suggestion
                onItemClick(e) {
```

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/10 Access a Node/10 Using a Method.md
> +            this.treeView.getNodes();
The function uses the component context (`this`), so it needs to be bound to that context in the constructor:
https://js.devexpress.com/Documentation/20_1/Guide/React_Components/Component_Configuration_Syntax/#Callback_Functions

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +			:searchExpr='searchExpr'  />
Too much indentation because tabs are used. Please make sure that your text editor inserts 4 spaces, not a tab symbol, when you press the Tab key.

2020-02-13 15:00 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +                    searchExpr={['count', 'name']} />
Declare arrays as constants or component properties to prevent unnecessary re-rendering of our components.

2020-02-14 07:25 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +        import { DxTreeView } from 'devextreme-vue/tree-view';
fixed

2020-02-14 07:25 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +                id: '1',
fixed

2020-02-14 07:25 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +                DxTreeView,
fixed

2020-02-14 07:26 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +    <!-- tab: App.js -->import React from 'react';
fixed

2020-02-14 07:26 UTC, novsstation commented on concepts/05 Widgets/TreeView/10 Access a Node/05 Within Event Handlers.md
> +                onItemClick(e){
fixed

2020-02-14 07:26 UTC, novsstation commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +			:searchExpr='searchExpr'  />
fixed

2020-02-14 07:26 UTC, novsstation commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +                    searchExpr={['count', 'name']} />
fixed

2020-02-14 07:26 UTC, novsstation commented on concepts/05 Widgets/TreeView/10 Access a Node/10 Using a Method.md
> +            this.treeView.getNodes();
fixed

2020-02-14 07:26 UTC, novsstation commented on concepts/05 Widgets/TreeView/07 Use Plain Data.md
> +                    dataStructure='plain'
fixed

2020-02-14 07:27 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +        :items="hierarchicalData" />
fixed

2020-02-14 07:27 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +            id: '1',
fixed

2020-02-14 09:09 UTC, novsstation commented on concepts/05 Widgets/TreeView/00 Overview.md
> +        import { DxTreeView } from 'devextreme-vue/tree-view';
fixed

2020-02-14 09:09 UTC, novsstation commented on concepts/05 Widgets/TreeView/05 Use Hierarchical Data.md
> +            keyExpr='key'
fixed

2020-02-17 12:17 UTC, RomanTsukanov requested changes

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/00 Overview.md
> +
```suggestion

```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/05 Use Hierarchical Data.md
> +    <!--HTML--><div id="treeViewContainer"></div>
There's no need for HTML in all these examples. If we added it, HTML and JavaScript would be displayed in tabs, with HTML as the _first_ tab. But HTML doesn't convey any information on the matter being described. As a result, the reader sees irrelevant code. That's why it is better to leave it out.

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/10 Access a Node/05 Within Event Handlers.md
> +            onItemClick(e){
```suggestion
            onItemClick(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/10 Access a Node/10 Using a Method.md
> +            getNodes(){
```suggestion
            getNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/10 Access a Node/10 Using a Method.md
> +        getNodes(e){
```suggestion
        getNodes(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +            :search-enabled=true
```suggestion
            :search-enabled="true"
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +            :search-enabled=true
```suggestion
            :search-enabled="true"
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +                    searchExpr={["count", "name"]} />
Declare the array as a constant.

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +        const searchExpr = ["count", "name"];
Move this out of the class declaration.

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +            :search-enabled=true>
```suggestion
            :search-enabled="true">
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +                width=300
```suggestion
                :width="300"
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +            DxTreeView DxSearchEditorOptions
```suggestion
            DxTreeView,
            DxSearchEditorOptions
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +    import {TreeView, SearchEditorOptions} from 'devextreme-react/tree-view';
```suggestion
    import { TreeView, SearchEditorOptions } from 'devextreme-react/tree-view';
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +                    searchEnabled={true} >
```suggestion
                    searchEnabled={true}>
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +                expandAllNodes(){
```suggestion
                expandAllNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +                collapseAllNodes(){
```suggestion
                collapseAllNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +            expandAllNodes(e){
```suggestion
            expandAllNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +            collapseAllNodes(e){
```suggestion
            collapseAllNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +                this.treeView.collapseAll();
These functions use the component's context (`this`), so you need to bind them to it in the constructor (second example [in this article](https://js.devexpress.com/Documentation/20_1/Guide/React_Components/Component_Configuration_Syntax/#Call_Methods))

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +                expandNode(key){
```suggestion
                expandNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +                collapseNode(key){
```suggestion
                collapseNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +            expandNode(key){
```suggestion
            expandNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +            collapseNode(key){
```suggestion
            collapseNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/10 Events.md
> +            onItemExpanded(e){
```suggestion
            onItemExpanded(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/10 Events.md
> +            onItemCollapsed(e){
```suggestion
            onItemCollapsed(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/10 Events.md
> +        onItemExpanded(e){
```suggestion
        onItemExpanded(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/10 Events.md
> +        onItemCollapsed(e){
```suggestion
        onItemCollapsed(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +            selectNode(key){
```suggestion
            selectNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +            unselectNode(key){
```suggestion
            unselectNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +        selectNode(key){
```suggestion
        selectNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +        unselectNode(key){
```suggestion
        unselectNode(key) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +            unselectAllNodes(){
```suggestion
            selectAllNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +            unselectAllNodes(){
```suggestion
            unselectAllNodes() {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +        selectAllNodes(e){
```suggestion
        selectAllNodes(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/02 Using the API.md
> +        unselectAllNodes(e){
```suggestion
        unselectAllNodes(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/05 User Interaction.md
> +            :select-by-click=true
```suggestion
            :select-by-click="true"
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/05 User Interaction.md
> +                    showCheckBoxesMode="normal" /> // or 'selectAll'
```suggestion
                    showCheckBoxesMode="normal" /> {/* or 'selectAll' */}
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/10 Events.md
> +            onItemSelectionChanged(e){
```suggestion
            onItemSelectionChanged(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/10 Events.md
> +            onSelectionChanged(e){
```suggestion
            onSelectionChanged(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/10 Events.md
> +        onItemSelectionChanged(e){
```suggestion
        onItemSelectionChanged(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/10 Events.md
> +        onSelectionChanged(e){
```suggestion
        onSelectionChanged(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/25 Select Nodes/10 Events.md
> +        onSelectAllValueChanged(e){
```suggestion
        onSelectAllValueChanged(e) {
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/30 Customize Node Appearance.md
> +        function renderTreeViewItem(item) {
I'm not sure that you can declare a function this way only inside the component

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/30 Customize Node Appearance.md
> +            return (<i>{item.text}</i>);
```suggestion
            return (
                <i>{item.text}</i>
            );
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/32 Enhance Performance on Large Datasets.md
> +            :root-value=-1
```suggestion
            :root-value="-1"
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/32 Enhance Performance on Large Datasets.md
> +            let parentId = parent ? parent.itemData.id : '';
```suggestion
            const parentId = parent ? parent.itemData.id : '';
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/32 Enhance Performance on Large Datasets.md
> +            let parentId = parent ? parent.itemData.id : '';
Move function contents 4 spaces to the right, and you will find that there is a closing bracket missing.

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/32 Enhance Performance on Large Datasets.md
> +            let parentId = parent ? parent.itemData.id : '';
```suggestion
            const parentId = parent ? parent.itemData.id : '';
```

2020-02-17 12:17 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeView/35 Keyboard Support.md
> +            this.componentDidMount = this.componentDidMount.bind(this);
I think `componentDidMount()` is executed in the component's context because it is a React hook.

2020-02-17 12:36 UTC, novsstation commented on concepts/05 Widgets/TreeView/32 Enhance Performance on Large Datasets.md
> +            let parentId = parent ? parent.itemData.id : '';
It seems all is fine

![image](https://user-images.githubusercontent.com/57402891/74654384-3d648500-519b-11ea-8a9f-93e416f9b1fa.png)

2020-02-17 12:37 UTC, novsstation commented on concepts/05 Widgets/TreeView/35 Keyboard Support.md
> +            this.componentDidMount = this.componentDidMount.bind(this);
Fixed

2020-02-17 12:38 UTC, novsstation commented on concepts/05 Widgets/TreeView/05 Use Hierarchical Data.md
> +    <!--HTML--><div id="treeViewContainer"></div>
Fixed

2020-02-17 12:43 UTC, novsstation commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +                    searchExpr={["count", "name"]} />
Fixed

2020-02-17 12:44 UTC, novsstation commented on concepts/05 Widgets/TreeView/15 Search Nodes.md
> +        const searchExpr = ["count", "name"];
Fixed

2020-02-17 13:02 UTC, novsstation commented on concepts/05 Widgets/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
> +                this.treeView.collapseAll();
Fixed https://github.com/DevExpress/devextreme-documentation/pull/310/commits/19407bc03bc153c5ccccce009513b11d25190492

2020-02-17 13:44 UTC, RomanTsukanov approved these changes

2020-02-17 13:58 UTC, merged