Add Vue and React examples for the NumberBox
DevExpress/devextreme-documentation pull request #330
Opened 2020-02-13 13:28 UTC by DokaRus

2020-02-14 11:58 UTC, AlexJameson approved these changes

2020-02-14 11:58 UTC, AlexJameson commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +                <NumberBox onValueChanged="numberBoxValueChanged" />
```suggestion
                <NumberBox onValueChanged={this.numberBoxValueChanged} />
```

2020-02-14 11:58 UTC, AlexJameson commented on concepts/05 Widgets/NumberBox/20 Keyboard Support.md
> +                <NumberBox onInitialized="registerKeyHandlers" />
If function call fix is applied above, apply it here as well.

2020-02-17 13:23 UTC, RomanTsukanov requested changes

2020-02-17 13:23 UTC, RomanTsukanov commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +            valueChangeEvent="keyup"
```suggestion
            value-change-event="keyup"
```

2020-02-17 13:23 UTC, RomanTsukanov commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +        numberBox_valueChanged ({ previousValue, value: newValue }) {
It looks like in Angular and Vue we should show two-way binding and in React state changing.

2020-02-17 13:23 UTC, RomanTsukanov commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +        <DxNumberBox @valueChanged="numberBoxValueChanged" />
```suggestion
        <DxNumberBox @value-changed="numberBoxValueChanged" />
```

2020-02-17 13:23 UTC, RomanTsukanov commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +                <NumberBox onValueChanged="numberBoxValueChanged" />
```suggestion
                <NumberBox onValueChanged={this.numberBoxValueChanged} />
```

2020-02-17 13:23 UTC, RomanTsukanov commented on concepts/05 Widgets/NumberBox/20 Keyboard Support.md
> +        <DxNumberBox @initialized="registerKeyHandlers"
We usually call `registerKeyHandler` on `mounted`/`componentDidMount()`:
https://js.devexpress.com/Documentation/20_1/Guide/Widgets/Button/Keyboard_Support/

2020-02-17 15:18 UTC, DokaRus commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +        numberBox_valueChanged ({ previousValue, value: newValue }) {
[please notice] (https://github.com/DevExpress/devextreme-documentation/pull/331#discussion_r380236985)

2020-02-18 14:39 UTC, RomanTsukanov commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +        numberBox_valueChanged ({ previousValue, value: newValue }) {
Let's do here what you've done on the Calendar PR.

2020-02-18 15:27 UTC, DokaRus commented on concepts/05 Widgets/NumberBox/10 Handle the Value Change Event.md
> +        numberBox_valueChanged ({ previousValue, value: newValue }) {
Done

2020-02-18 15:46 UTC, RomanTsukanov approved these changes

2020-02-18 15:51 UTC, merged