Add React and Vue snippets to dxDataGrid.onExporting
DevExpress/devextreme-documentation pull request #348
Opened 2020-02-18 12:56 UTC by onebalaban

2020-02-18 14:59 UTC, RomanTsukanov requested changes

2020-02-18 14:59 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +            data-field="ID"
```suggestion
                data-field="ID"
```

2020-02-18 14:59 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +            :visible="false"
```suggestion
                :visible="false"
```

2020-02-18 14:59 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +    import { DxDataGrid } from 'devextreme-vue/data-grid';
```suggestion
    import { DxDataGrid, DxColumn } from 'devextreme-vue/data-grid';
```

2020-02-18 14:59 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +                    <DxColumn dataField="ID" visible={false} />
```suggestion
                    <Column dataField="ID" visible={false} />    
```

2020-02-18 15:44 UTC, RomanTsukanov approved these changes

2020-02-19 09:08 UTC, artem-kurchenko approved these changes

2020-02-19 09:11 UTC, merged