PDF - documentation draft
DevExpress/devextreme-documentation pull request #3497
Opened 2022-03-04 08:10 UTC by novsstation

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
> +The color must have in the following format: hexadecimal color.
The color must **be** in the following format: hexadecimal color.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Allows to specify custom width for the exporting columns of the DataGrid. Uses the measure units, which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20St
Uses the measure units which are specified in the constructor **of** the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.

(убрать запятую перед which)

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Allows you to prevent default drawing logic
точка

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +A DataGrid cell
точка

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Object containign information about location of the cell and it's dimensions. An object with the following content: *{ x: numeric, y: numeric, h: numeric, w: numeric }*.
Object **that contains** information about location of the cell and **its** dimensions.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
> +Specifies the value of the horizontal gap between data cells and groups and headers. Uses the measure units, which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/
Имеется в виду, что indent будет между клетками И (группами и хэдерами) или между клетками, группами и хэдерами?

Uses the measure units which are specified in the constructor **of** the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object. (убрать запятую перед which)

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/bottom.md
> +Generates space from the bottom side of the page.
Generates space **at** the bottom of the page.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/left.md
> +Generates space from the left side of the page.
Generates space **at** the left side of the page.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
> +Generates space, around the exported DataGrid. Uses the measure units, which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridP
Generates space around the exported DataGrid. Uses the measure units which are specified in the constructor **of** the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
(внимание на убранные запятые)

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/right.md
> +Generates space from the right side of the page.
Generates space **at** the right side of the page.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
> +A function that is executed before the row of the DataGrid is exported. Allows you to custimize the height of the exported row.
Allows you to **customize** the height of the exported row.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
> +Allows you to specify the minimum height of the exported row. If the specified value is less than the height of the text, then the row height will be automatically increased so that the text has enou
If the specified value is less than the height of the text, the row height will be automatically increased.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/backgroundColor.md
> +The color must have in the following format: hexadecimal colors
The color must **be** in the following format: hexadecimal color.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/name.md
> +Specify the name of the used font. Default font names are listed below:
**Specifies** the name of the used font.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/size.md
> +Specify the size of the used font.
**Specifies** the size of the used font.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/style.md
> +Specify the style of the used font.
**Specifies** the style of the used font.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/bottom.md
> +Generates the space from the bottom side of the cell inside the DataGrid
Generates space **at** the bottom side of the cell inside the DataGrid. (точка)

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/left.md
> +Generates the space from the left side of the cell inside the DataGrid.
Generates space **at** the left side of the cell inside the DataGrid.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/padding.md
> +Generates space around the text of the cell inside the DataGrid. Uses the measure units, which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/
Uses the measure units which are specified in the constructor **of** the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/right.md
> +Generates the space from the right side of the cell inside the DataGrid
Generates space **at** the right side of the cell inside the DataGrid. (точка)

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/top.md
> +Generates the space from the top side of the cell inside the DataGrid
Generates space **at** the top side of the cell inside the DataGrid. (точка)

2022-03-04 10:48 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/wordWrapEnabled.md
> +The default value depends on the value of the grid's [wordWrapEnabled](/api-reference/10%20UI%20Components/GridBase/1%20Configuration/wordWrapEnabled.md '/Documentation/ApiReference/UI_Components/dxD
The default value depends on the value of the **DataGrid** [wordWrapEnabled](/api-reference/10%20UI%20Components/GridBase/1%20Configuration/wordWrapEnabled.md '/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/#wordWrapEnabled') option.

2022-03-04 11:46 UTC, novsstation commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
> +Specifies the value of the horizontal gap between data cells and groups and headers. Uses the measure units, which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/
Сорри, очень расплывчато написал. Лучше заменить слово ячейки - на строчки.
Т.е. индент - горизонтальный отступ для строчек с данными, относительно заголовков и групп.

![image](https://user-images.githubusercontent.com/57402891/156757871-c2be6d7c-09a0-47ca-8238-4412c02d6fec.png)

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
> +Specifies the color of the outer borders of the Table.
Table точно должно быть с большой буквы? У нас только названия контролов с больших букв пишутся

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
> +Specifies the width of the outer borders of the Table. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDa
То же замечание про Table

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Object that contains information about location of the cell and it's dimensions. An object with the following content: *{ x: numeric, y: numeric, h: numeric, w: numeric }*.
Object that contains information about the location of the cell and its dimensions. An object with the following content: *{ x: numeric, y: numeric, h: numeric, w: numeric }*.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/right.md
> +Generates space at the right of the page.
Generates space at the right side of the page.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/repeatHeaders.md
> +Specifies whether or not to repeat the grid headers on each page.
Specifies whether or not to repeat the DataGrid headers on each page.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/topLeft.md
> +A start position inside the page used for export of the DataGrid. Contains **x** and **y** properties. This position starts from the page margins.
Specifies a starting position for DataGrid export on the page. Contains **x** and **y** properties. You can locate this position only below the page margins.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/padding.md
> +Generates space around the text of the cell inside the DataGrid. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/P
Generates space around the text of the cell inside the DataGrid. Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/font.md
> +Object containing information about the **size**, **name** and **style** of the used font.
Object that contains information about the **size**, **name** and **style** of the used font.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/y.md
> +Allows you to specify vertical position of the exported grid.
Allows you to specify vertical position of the exported DataGrid.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/x.md
> +Allows you to specify horizontal position of the exported grid.
Allows you to specify horizontal position of the exported DataGrid.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/left.md
> +Generates space at the left of the page.
Generates space at the left side of the page.

2022-03-04 13:38 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
> +Specifies the value of the horizontal gap between data cells and groups and headers. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/O
Specifies the value of the horizontal gap between data cells and groups and headers. Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
> +Specifies the color of the outer borders of the table.
Specifies the color of the table's outer borders.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
> +Specifies the width of the outer borders of the table. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDa
Specifies the width of the table's outer borders.

Can you please transfer the second sentence to the fullDescription?

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Allows to specify custom width for the exporting columns of the DataGrid. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Str
Transfer the second sentence to the fullDescription.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Instance of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#js
Instance of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument').

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Object that contains information about the location of the cell and its dimensions. An object with the following content: { x: numeric, y: numeric, h: numeric, w: numeric }.
Object that contains information about the location of the cell and its dimensions. An object with the following structure: { x: numeric, y: numeric, h: numeric, w: numeric }.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
> +Specifies the value of the horizontal gap between data cells and groups and headers. Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Ob
Can we maybe add an image that illustrates this indent?

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/left.md
> +Generates space at the left side of the page.
Specifies the margin at the left side of the page.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
> +Generates space around the exported DataGrid. Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProp
Specifies the margin around the exported Grid.

Transfer the second sentence to the fullDescription.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/right.md
> +Generates space at the right side of the page.
Specifies the margin at the right side of the page.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/top.md
> +Generates space at the top of the page.
Specifies the margin at the top of the page.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/bottom.md
> +Generates space at the bottom side of the cell inside the DataGrid.
Specifies the padding at the bottom of the DataGrid cell.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/left.md
> +Generates space at the left side of the cell inside the DataGrid.
Specifies the padding at the left side of the DataGrid cell.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/padding.md
> +Generates space around the text of the cell inside the DataGrid. Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/Pd
Specifies the padding around the text of the DataGrid cell.

Transfer the second sentence to the fullDescription.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/right.md
> +Generates space at the right side of the cell inside the DataGrid.
Specifies the padding at the right side of the DataGrid cell.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/padding/top.md
> +Generates space at the top side of the cell inside the DataGrid.
Specifies the padding at the top of the DataGrid cell.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
> +Allows you to specify the minimum height of the exported row. If the specified value is less than the height of the text, the row height will be automatically increased.
If the specified value is less than the height of the text, the component increases the row height automatically.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/repeatHeaders.md
> +Specifies whether or not to repeat the DataGrid headers on each page.
Specifies whether to repeat the DataGrid headers on each page.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/topLeft.md
> +Specifies a starting position for DataGrid export on the page. Contains **x** and **y** properties. You can locate this position only below the page margins.
Specifies a start position for DataGrid export on the page. Contains **x** and **y** properties. You can locate this position only below the page margins.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/font.md
> +Object that contains information about the **size**, **name** and **style** of the used font.
Object that contains information about the font's **size**, **name** and **style**.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/name.md
> +Specifies the name of the used font. Default font names are listed below:
Specifies the name of the font. Default font names:

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/size.md
> +Specifies the size of the used font.
Specifies the size of the font.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/font/style.md
> +Specifies the style of the used font.
Specifies the style of the font.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/horizontalAlign.md
> +The default alignment of the content depends on the [type of data](/api-reference/_hidden/GridBaseColumn/dataType.md '{basewidgetpath}/Configuration/columns/#dataType').
The default alignment of the content depends on the [dataType](/api-reference/_hidden/GridBaseColumn/dataType.md '{basewidgetpath}/Configuration/columns/#dataType').

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/textColor.md
> +Specifies the color of the text for the cell.
Specifies the text color for the cell.

2022-03-17 11:16 UTC, vladaskorohodova commented on api-reference/_hidden/PdfCell/wordWrapEnabled.md
> +The default value depends on the value of the DataGrid [wordWrapEnabled](/api-reference/10%20UI%20Components/GridBase/1%20Configuration/wordWrapEnabled.md '/Documentation/ApiReference/UI_Components/d
The default value depends on the value of the DataGrid [wordWrapEnabled](/api-reference/10%20UI%20Components/GridBase/1%20Configuration/wordWrapEnabled.md '/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/#wordWrapEnabled') property.

2022-03-25 04:51 UTC, EugeniyKiyashko commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
> +Specifies the width of the outer borders of the table. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDa
Yes, certainly

2022-03-25 04:53 UTC, EugeniyKiyashko commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Allows to specify custom width for the exporting columns of the DataGrid. Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Str
Fixed

2022-03-25 04:56 UTC, EugeniyKiyashko commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Instance of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#js
Fixed. Check it, please

2022-03-28 08:26 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
> +Specifies the value of the horizontal gap between data cells and groups and headers.
```suggestion
Specifies the length of the horizontal gap between DataGrid group headers and rows.
```

2022-03-28 08:35 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
> +Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReferen
```suggestion
Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
```

2022-03-28 08:35 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Uses the measure units which are specified in the constructor for the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReferen
```suggestion
Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
```

2022-03-28 08:35 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +A function that is executed before the cell of the DataGrid is exported. Allows you to draw any content inside the cell of the exported PDF file.
```suggestion
A function that allows you to draw a content inside the cell of the exported DataGrid. This function is executed before the cell export.
```

2022-03-28 08:35 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/bottom.md
> +Generates space at the bottom of the page.
```suggestion
Specifies the margin at the bottom of the page.
```

2022-03-28 08:35 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
> +A function that is executed before the row of the DataGrid is exported. Allows you to customize the height of the exported row.
```suggestion
A function that allows you to customize the height of the exported row. This function is executed before the row export.
```

2022-03-31 13:29 UTC, AnnaKondratova requested changes

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
> +The color must be in the following format: hexadecimal color.
```suggestion
The color must be in the hexadecimal format.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Instance of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#js
```suggestion
An instance of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +A function that allows you to draw a content inside the cell of the exported DataGrid. This function is executed before the cell export.
```suggestion
A function that allows you to draw a cell content of the exported DataGrid. This function is executed before the cell export.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Allows to specify custom width for the exporting columns of the DataGrid.
```suggestion
Specifies a custom width for the exporting DataGrid columns.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Object that contains information about the location of the cell and its dimensions. An object with the following structure: { x: numeric, y: numeric, h: numeric, w: numeric }.
```suggestion
Object that contains information about the location of the cell and its dimensions. An object has the following structure: { x: numeric, y: numeric, h: numeric, w: numeric }.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
> +Specifies the margin around the exported Grid.
```suggestion
Specifies the margin for the top, bottom, left, and right sides of the exported Grid.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
> +Cells for the currently exporting row.
```suggestion
An array of cells of the exported row.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
> +Allows you to specify the minimum height of the exported row. If the specified value is less than the height of the text, the component increases the row height automatically.
```suggestion
Specifies the height of the exported row. If the specified value is less than the height of the text, the component increases the row height automatically.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/repeatHeaders.md
> +Specifies whether to repeat the DataGrid headers on each page.
```suggestion
Specifies whether to repeat the DataGrid column headers on each page.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/x.md
> +Allows you to specify horizontal position of the exported DataGrid.
```suggestion
Specifies the horizontal position of the exported DataGrid.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/y.md
> +Allows you to specify vertical position of the exported DataGrid.
```suggestion
Specifies the vertical position of the exported DataGrid.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
>  You can call this method at any point in your application. In this example, we call this method in a standalone button's [onClick](/api-reference/10%20UI%20Components/dxButton/1%20Configuration/onCli
```suggestion
You can call this method at any point in your application. In this example, this method is called in a standalone button's [onClick](/api-reference/10%20UI%20Components/dxButton/1%20Configuration/onClick.md '/Documentation/ApiReference/UI_Components/dxButton/Configuration/#onClick') handler:
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/backgroundColor.md
> +Specifies the background color for the cell.
```suggestion
Specifies the background color of the cell.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/backgroundColor.md
> +The color must be in the following format: hexadecimal color.
```suggestion
The color must be in the hexadecimal format.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/font/font.md
> +Object that contains information about the font's size, name and style.
```suggestion
An object that contains information about the font's size, name and style.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/font/name.md
> +Specifies the name of the font. Default font names:
```suggestion
Specifies the font name. Default font names:
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/font/size.md
> +Specifies the size of the font.
```suggestion
Specifies the font size.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/font/style.md
> +Specifies the style of the font.
```suggestion
Specifies the font style.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/padding/bottom.md
> +Specifies the padding at the bottom of the DataGrid cell.
```suggestion
Specifies the bottom padding of the DataGrid cell.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/padding/left.md
> +Specifies the padding at the left side of the DataGrid cell.
```suggestion
Specifies the left padding of the DataGrid cell.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/padding/padding.md
> +Specifies the padding around the text of the DataGrid cell.
```suggestion
Specifies the top, bottom, left, and right paddings of the DataGrid cell.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/padding/right.md
> +Specifies the padding at the right side of the DataGrid cell.
```suggestion
Specifies the right padding of the DataGrid cell.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/padding/top.md
> +Specifies the padding at the top of the DataGrid cell.
```suggestion
Specifies the top padding of the DataGrid cell.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/text.md
> +The cell's raw text.
```suggestion
The cell's text.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/wordWrapEnabled.md
> +Specifies whether to enable word wrapping for exported data in the resulting PDF file.
```suggestion
Specifies whether to enable word wrapping in the resulting PDF file.
```

2022-03-31 13:29 UTC, AnnaKondratova commented on api-reference/_hidden/PdfCell/wordWrapEnabled.md
> +The default value depends on the value of the DataGrid [wordWrapEnabled](/api-reference/10%20UI%20Components/GridBase/1%20Configuration/wordWrapEnabled.md '/Documentation/ApiReference/UI_Components/d
```suggestion
The default value depends on the value of the DataGrid's [wordWrapEnabled](/api-reference/10%20UI%20Components/GridBase/1%20Configuration/wordWrapEnabled.md '/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/#wordWrapEnabled') property.
```

2022-03-31 14:06 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/topLeft.md
> +Specifies a starting position for DataGrid export on the page. Contains x and y properties. You can locate this position only below the page margins.
```suggestion
Specifies the top left position of the DataGrid in the exported PDF document. Contains x and y properties. You can locate this position only below the page margins.
```

2022-04-01 19:16 UTC, albertov05 commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
> +Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReferenc
```suggestion
Uses the measure units that are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
```

2022-04-01 19:20 UTC, albertov05 commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Specifies a custom width for the exporting DataGrid columns.
Can we change "exporting" to "exported"?

2022-04-01 19:20 UTC, albertov05 commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReferenc
```suggestion
Uses the measure units that are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
```

2022-04-01 19:21 UTC, albertov05 commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +A function that allows you to draw a cell content of the exported DataGrid. This function is executed before the cell export.
```suggestion
A function that allows you to draw cell content of the exported DataGrid. This function is executed before the cell is exported.
```

2022-04-01 19:24 UTC, albertov05 commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
> +Object that contains information about the location of the cell and its dimensions. An object has the following structure: { x: numeric, y: numeric, h: numeric, w: numeric }.
```suggestion
An object that contains information about the location of the cell and its dimensions. The object has the following structure: { x: numeric, y: numeric, h: numeric, w: numeric }.
```

2022-04-01 19:41 UTC, albertov05 commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
> +Uses the measure units which are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReferenc
```suggestion
Uses the measure units that are specified in the constructor of the [jsPDFDocument](/api-reference/50%20Common/Object%20Structures/PdfExportDataGridProps/jsPDFDocument.md '/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#jsPDFDocument') object.
```

2022-04-01 19:57 UTC, albertov05 commented on api-reference/_hidden/PdfCell/font/font.md
> +An object that contains information about the font's size, name and style.
```suggestion
An object that contains information about the font's size, name, and style.
```

2022-04-01 21:07 UTC, albertov05 commented on api-reference/_hidden/PdfCell/font/name.md
> +* Time-Italic
```suggestion
* Times-Italic
```

2022-04-01 21:08 UTC, albertov05 commented on api-reference/_hidden/PdfCell/font/name.md
> +* Time-BoldItalic
```suggestion
* Times-BoldItalic
```

2022-04-01 21:15 UTC, albertov05 commented on api-reference/_hidden/PdfCell/textColor.md
> +The color must be in the following format: hexadecimal color.
```suggestion
The color must be in the hexadecimal format.
```

2022-04-04 05:56 UTC, vladaskorohodova commented on api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
> +Specifies a custom width for the exporting DataGrid columns.
```suggestion
Specifies a custom width for the exported DataGrid columns.
```

2022-04-04 07:04 UTC, vladaskorohodova approved these changes

2022-04-04 07:05 UTC, EugeniyKiyashko approved these changes

2022-04-04 07:08 UTC, AnnaKondratova approved these changes

2022-04-04 07:08 UTC, merged