Add Angular, Vue and React code snippets to dxTabPanel
DevExpress/devextreme-documentation pull request #418
Opened 2020-02-27 10:35 UTC by EugeniyKiyashko

2020-03-02 08:56 UTC, RomanTsukanov requested changes

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/00 Overview.md
> +    <div id='tabPanelContainer'></div>
Always use double quotes in the markup.

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/05 Customize Item Appearance.md
> +If you need a more flexible solution, define an [itemTemplate](/api-reference/10%20UI%20Widgets/dxTabPanel/1%20Configuration/itemTemplate.md '/Documentation/ApiReference/UI_Widgets/dxTabPanel/Configu
```suggestion
If you need a more flexible solution, define [itemTemplate](/api-reference/10%20UI%20Widgets/dxTabPanel/1%20Configuration/itemTemplate.md '/Documentation/ApiReference/UI_Widgets/dxTabPanel/Configuration/#itemTemplate') and [itemTitleTemplate](/api-reference/10%20UI%20Widgets/dxTabPanel/1%20Configuration/itemTitleTemplate.md '/Documentation/ApiReference/UI_Widgets/dxTabPanel/Configuration/#itemTitleTemplate') for views and tabs, respectively. In Angular and Vue, you can declare them in the markup. In React, you can use rendering functions (shown in the code below) or components.
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/05 Customize Item Appearance.md
> +					<p *ngFor="let key of getItemKeys(content.data)">
Please do not use tab symbols for indentation.

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/05 Customize Item Appearance.md
> +                }];
```suggestion
                }]
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/05 Customize Item Appearance.md
> +If you use jQuery, use <a href="http://api.jquery.com/category/manipulation/" target="_blank">DOM manipulation methods</a> to combine the HTML markup for tabpanel item. To apply this markup, use the
```suggestion
If you use jQuery, use <a href="http://api.jquery.com/category/manipulation/" target="_blank">DOM manipulation methods</a> to combine the HTML markup for **TabPanel** items. To apply this markup, use the **itemTemplate** and **itemTitleTemplate** callback functions as shown in the following code:
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +            items: [{
The data source doesn't add anything to the example. Let's remove it from all examples in this article.

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +        [selectedIndex]="1">
Let's two-way bind to the `selectedIndex` in Angular and Vue.

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +            this.state = {
```suggestion
            super(props);
            this.state = {
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +        </DxTabPanel>
```suggestion

```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +        </DxTabPanel>
```suggestion

```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +                </TabPanel>
```suggestion
                />
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +        </DxTabPanel>
```suggestion
        />
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +                </TabPanel>
```suggestion
                />
```

2020-03-02 08:56 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/15 Control the Behavior.md
> +                </TabPanel>
```suggestion
                />
```

2020-03-03 09:44 UTC, RomanTsukanov requested changes

2020-03-03 09:44 UTC, RomanTsukanov commented on concepts/05 Widgets/TabPanel/00 Overview.md
> +        [items]='tabPanelItems'>
```suggestion
        [items]="tabPanelItems">
```

2020-03-03 11:11 UTC, RomanTsukanov approved these changes

2020-03-03 12:28 UTC, jsdmitry approved these changes

2020-03-03 14:35 UTC, merged