Add Angular, Vue and React code snippets to dxScrollView
DevExpress/devextreme-documentation pull request #419
Opened 2020-02-27 16:01 UTC by EugeniyKiyashko

2020-03-02 14:31 UTC, RomanTsukanov requested changes

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/00 Overview.md
> +            :show-scrollbar="always">  <!-- or 'onScroll' | 'onHover' | 'never' -->
```suggestion
            show-scrollbar="always">  <!-- or 'onScroll' | 'onHover' | 'never' -->
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        scrollUpClick = e => {
```suggestion
        scrollUp() {
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        scrollDownClick = e => {
```suggestion
        scrollDown() { 
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        (onClick)="scrollUpClick($event)">
```suggestion
        (onClick)="scrollUp($event)">
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        (onClick)="scrollDownClick($event)">
```suggestion
        (onClick)="scrollDown($event)">
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        (onClick)="scrollDownClick($event)">
Please rename these functions in code examples for other frameworks.

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +                @click="scrollUpClick($event)">
```suggestion
                @click="scrollUp">
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +                @click="scrollDownClick($event)">
```suggestion
                @click="scrollDown">
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        (onClick)="scrollClick($event)">
```suggestion
        (onClick)="scroll($event)">
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        scrollClick = e => {
```suggestion
        scroll() {
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +            <!-- Scrolls the content to the element with the "end" id -->
```suggestion
            // Scrolls the content to the element with the "end" id
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +            {/* Scrolls the content to the element with the "end" id */}
```suggestion
            // Scrolls the content to the element with the "end" id
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +                <!-- Scrolls the content to the element with the "end" id -->
```suggestion
                // Scrolls the content to the element with the "end" id
```

2020-03-02 14:31 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/10 Handle Scroll Gestures.md
> +        scroll = (e) => {
```suggestion
        scroll(e) {
```

2020-03-03 09:49 UTC, RomanTsukanov requested changes

2020-03-03 09:49 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/00 Overview.md
> +            :use-native="false"F
```suggestion
            :use-native="false"
```

2020-03-03 09:49 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +        scrollClick = () => {
```suggestion
        scroll = () => {
```

2020-03-03 09:49 UTC, RomanTsukanov commented on concepts/05 Widgets/ScrollView/05 Scroll the Content/20 API.md
> +                    onClick={this.scrollClick}>
```suggestion
                    onClick={this.scroll}>
```

2020-03-04 11:42 UTC, RomanTsukanov approved these changes

2020-03-04 13:11 UTC, jsdmitry approved these changes

2020-03-04 14:22 UTC, merged