Add missing React and Vue code snippets to dxDataGrid.sortByGroupSummaryInfo
DevExpress/devextreme-documentation pull request #443
Opened 2020-03-04 07:03 UTC by onebalaban

2020-03-04 11:52 UTC, RomanTsukanov requested changes
onToolbarPreparing examples somehow sneaked into this PR.

2020-03-05 13:23 UTC, RomanTsukanov requested changes

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    summaryType="avg"
```suggestion
                    summary-type="avg"
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    summaryType="max"
```suggestion
                    summary-type="max"
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    summaryType="min"
```suggestion
                    summary-type="min"
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +            <DxSortByGroupSummaryInfo :summary-item="1"/> <!-- determines the maximum income item using its index in the "groupItems" array -->
```suggestion
            <DxSortByGroupSummaryInfo
                :summary-item="1"/> <!-- determines the maximum income item using its index in the "groupItems" array -->
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +            <DxSortByGroupSummaryInfo summary-item="min"/> <!-- determines the minimum tasks item using its aggregate function -->
```suggestion
            <DxSortByGroupSummaryInfo
                summary-item="min"/> <!-- determines the minimum tasks item using its aggregate function -->
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +            <DxSortByGroupSummaryInfo summary-item="Average Age Group Summary"/> <!-- determines the average age item using its name -->
```suggestion
            <DxSortByGroupSummaryInfo
                summary-item="Average Age Group Summary"/> <!-- determines the average age item using its name -->
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    <SortByGroupSummaryInfo summaryItem={1}/> {/* determines the maximum income item using its index in the "groupItems" array */}
```suggestion
                    <SortByGroupSummaryInfo
                        summaryItem={1}/> {/* determines the maximum income item using its index in the "groupItems" array */}
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    <SortByGroupSummaryInfo summaryItem="min"/> {/* determines the minimum tasks item using its aggregate function */}
```suggestion
                    <SortByGroupSummaryInfo
                        summaryItem="min"/> {/* determines the minimum tasks item using its aggregate function */}
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    <SortByGroupSummaryInfo summaryItem="Average Age Group Summary"/> {/* determines the average age item using its name */}
```suggestion
                    <SortByGroupSummaryInfo
                        summaryItem="Average Age Group Summary"/> {/* determines the average age item using its name */}
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +            <DxSortByGroupSummaryInfo summary-item="Average Age Group Summary"/> <!-- applies sorting regardless the grouping column -->
```suggestion
            <DxSortByGroupSummaryInfo
                summary-item="Average Age Group Summary"
            /> <!-- applies sorting regardless the grouping column -->
```

2020-03-05 13:23 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
> +                    <SortByGroupSummaryInfo summaryItem="Average Age Group Summary"/> {/* applies sorting regardless the grouping column */}
```suggestion
                    <SortByGroupSummaryInfo
                        summaryItem="Average Age Group Summary"
                    /> {/* applies sorting regardless the grouping column */}
```

2020-03-05 14:23 UTC, RomanTsukanov approved these changes

2020-03-05 15:36 UTC, artem-kurchenko approved these changes

2020-03-06 08:06 UTC, merged