Add Vue and React code snippets to dxResponsiveBox
DevExpress/devextreme-documentation pull request #454
Opened 2020-03-04 18:22 UTC by EugeniyKiyashko

2020-03-06 16:15 UTC, RomanTsukanov requested changes

2020-03-06 16:15 UTC, RomanTsukanov commented on concepts/05 Widgets/ResponsiveBox/10 Create the Layout Grid.md
> +            <!-- ... -->
```suggestion
            <DxCol/>
```

2020-03-06 16:15 UTC, RomanTsukanov commented on concepts/05 Widgets/ResponsiveBox/10 Create the Layout Grid.md
> +                    {/* ... */}
```suggestion
                    <Col/>
```

2020-03-06 16:15 UTC, RomanTsukanov commented on concepts/05 Widgets/ResponsiveBox/15 Arrange Layout Elements.md
> +            <!-- ... -->
```suggestion

```

2020-03-06 16:15 UTC, RomanTsukanov commented on concepts/05 Widgets/ResponsiveBox/15 Arrange Layout Elements.md
> +                    {/* ... */}
```suggestion

```

2020-03-06 16:15 UTC, RomanTsukanov commented on concepts/05 Widgets/ResponsiveBox/15 Arrange Layout Elements.md
> +            singleColumnScreen="xs sm">   <!-- Single-column layout on small and extra small screens -->
```suggestion
            single-column-screen="xs sm">   <!-- Single-column layout on small and extra small screens -->
```

2020-03-10 13:53 UTC, RomanTsukanov approved these changes

2020-03-11 09:13 UTC, jsdmitry approved these changes

2020-03-11 09:15 UTC, merged