Describe the confirmDelete option
DevExpress/devextreme-documentation pull request #49
Opened 2019-12-26 15:29 UTC by AlexJameson

2019-12-27 10:50 UTC, RomanTsukanov submitted a review, later dismissed

2019-12-27 10:50 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/GridBase/1 Configuration/editing/confirmDelete.md
> +Specifies if the confirmation is required when you delete a row.
```suggestion
Specifies if the confirmation is required when a user deletes a row.
```

2019-12-27 11:09 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/GridBase/1 Configuration/editing/confirmDelete.md
> +Specifies if the confirmation is required when you delete a row.
We also need to edit this description: https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/texts/#confirmDeleteMessage

2020-01-17 14:44 UTC, RomanTsukanov requested changes

2020-01-17 14:44 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeList/20 Editing/20 API/30 Delete.md
> +            this.grid.instance.deleteRow(1);
```suggestion
            this.treeList.deleteRow(1);
```

2020-01-17 14:44 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeList/20 Editing/20 API/30 Delete.md
> +                    :ref="gridRef">
```suggestion
                    ref={this.treeListRef}>
```

2020-01-17 14:44 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeList/20 Editing/20 API/30 Delete.md
> +            this.grid.instance.undeleteRow(1);
```suggestion
            this.treeList.undeleteRow(1);
```

2020-01-17 14:44 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeList/20 Editing/20 API/30 Delete.md
> +                    :ref="gridRef"
```suggestion
                    ref={this.treeListRef}
```

2020-01-17 15:32 UTC, RomanTsukanov approved these changes

2020-01-20 08:03 UTC, vconst approved these changes

2020-01-20 09:59 UTC, RomanTsukanov requested changes

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/10 User Interaction/10 Row Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDele
Something is wrong with the link. Try copy-pasting the URL and making a commit - the pre-commit hook should fix it.

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/10 User Interaction/10 Row Mode.md
> +            [allowDeleting]="true">
```suggestion
            [confirmDelete]="false">
```

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/10 User Interaction/20 Cell Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/con
The same link problem

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/20 API/30 Delete.md
> +Call the [deleteRow(rowIndex)](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/deleteRow(rowIndex).md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#deleteRowrowIndex') method to d
Here too

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/20 API/30 Delete.md
> +            ref="DataGrid">
Write ref names is lowerCamelCase. Please make this change in all these code samples.

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/20 API/30 Delete.md
> +        get DataGrid() {
Since this is a variable, it too should be in lowerCamelCase

2020-01-20 09:59 UTC, RomanTsukanov commented on concepts/05 Widgets/TreeList/20 Editing/10 User Interaction/20 Cell Mode.md
> +##### Vue
Angular and jQuery examples here still use the old approach to hiding the message. Please double check all the topics.

2020-01-20 11:50 UTC, RomanTsukanov requested changes

2020-01-20 11:50 UTC, RomanTsukanov commented on concepts/05 Widgets/DataGrid/20 Editing/20 API/30 Delete.md
> +                this.$refs.DataGrid.instance.deleteRow(1);
```suggestion
                this.$refs.dataGrid.instance.deleteRow(1);
```

2020-01-20 13:21 UTC, RomanTsukanov approved these changes

2020-01-20 17:47 UTC, arminal commented on api-reference/10 UI Widgets/GridBase/1 Configuration/editing/confirmDelete.md
> +Specifies if the confirmation is required when a user deletes a row.
```suggestion
Specifies if confirmation is required when a user deletes a row.
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/DataGrid/20 Editing/10 User Interaction/10 Row Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDele
```suggestion
Clicking the *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#confirmDelete') option to hide this dialog:
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/DataGrid/20 Editing/10 User Interaction/10 Row Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDele
incomplete sentence:
[confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#confirmDelete') option to hide this dialog:

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/DataGrid/20 Editing/10 User Interaction/20 Cell Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/con
```suggestion
Clicking the *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#confirmDelete') option to hide this dialog:
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/DataGrid/20 Editing/20 API/30 Delete.md
> +Call the [deleteRow(rowIndex)](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/deleteRow(rowIndex).md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#deleteRowrowIndex') method to d
```suggestion
Call the [deleteRow(rowIndex)](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/deleteRow(rowIndex).md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#deleteRowrowIndex') method to delete a specific row from the data source. This method invokes a confirmation dialog that allows a user to cancel deletion. The [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#confirmDelete') option allows you to hide this dialog instantly deleting the selected row from the data source:
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/DataGrid/20 Editing/20 API/30 Delete.md
>  Note that in the [batch mode](/concepts/05%20Widgets/DataGrid/20%20Editing/10%20User%20Interaction/30%20Batch%20Mode.md '/Documentation/Guide/Widgets/DataGrid/Editing/#User_Interaction/Batch_Mode') a
```suggestion
Note that in [batch mode](/concepts/05%20Widgets/DataGrid/20%20Editing/10%20User%20Interaction/30%20Batch%20Mode.md '/Documentation/Guide/Widgets/DataGrid/Editing/#User_Interaction/Batch_Mode') a row is only marked as deleted. To save changes, call the [saveEditData()](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/saveEditData().md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#saveEditData') method. Calling the [undeleteRow(rowIndex)](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/undeleteRow(rowIndex).md '/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#undeleteRowrowIndex') method cancels row deletion.
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/TreeList/20 Editing/10 User Interaction/10 Row Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/con
```suggestion
Clicking the *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/editing/#confirmDelete') option to hide this dialog:
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/TreeList/20 Editing/10 User Interaction/20 Cell Mode.md
> +Clicking a *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/con
```suggestion
Clicking the *"Delete"* button invokes the confirmation dialog that allows a user to cancel row deletion. Use the [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/editing/#confirmDelete') option to hide this dialog:
```

2020-01-20 17:47 UTC, arminal commented on concepts/05 Widgets/TreeList/20 Editing/20 API/30 Delete.md
> +Call the [deleteRow(rowIndex)](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/deleteRow(rowIndex).md '/Documentation/ApiReference/UI_Widgets/dxTreeList/Methods/#deleteRowrowIndex') method to d
```suggestion
Call the [deleteRow(rowIndex)](/api-reference/10%20UI%20Widgets/GridBase/3%20Methods/deleteRow(rowIndex).md '/Documentation/ApiReference/UI_Widgets/dxTreeList/Methods/#deleteRowrowIndex') method to delete a specific row from the data source. This method invokes a confirmation dialog that allows a user to cancel deletion. The [confirmDelete](/api-reference/10%20UI%20Widgets/GridBase/1%20Configuration/editing/confirmDelete.md '/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/editing/#confirmDelete') option allows you to hide this dialog instantly deleting the selected row from the data source:
```

2020-01-21 09:53 UTC, merged