Describe the Chart custom axes position API
DevExpress/devextreme-documentation pull request #501
Opened 2020-03-16 13:47 UTC by AlexJameson

2020-03-16 14:07 UTC, dxBeardedBear approved these changes

2020-03-16 14:13 UTC, RomanTsukanov requested changes
It is unclear how this option interacts with the [position](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/argumentAxis/#position) option.

2020-03-17 06:27 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/offset.md
> +Negative numbers shift the axis position to the top, positive numbers - to the bottom. If the [rotated](/api-reference/20%20Data%20Visualization%20Widgets/dxChart/1%20Configuration/rotated.md '/Docum
I think we need to give links to the positioning API here.

2020-03-17 13:15 UTC, RomanTsukanov approved these changes

2020-03-18 10:03 UTC, merged