DataGrid: add Accessibility topic
DevExpress/devextreme-documentation pull request #5024
Opened 2023-05-15 12:13 UTC by vladaskorohodova

2023-05-16 15:08 UTC, Alyar666 requested changes

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/05 Accessibility Features Overview.md
Let's write support level without icons. Instead, write in words (Supports, Supports with exceptions)

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>HeaderFilter icons do not have <code>alt</code> attributes.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Filter icons in the filter row do not have aria-label attributes.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Summaries are not pronounced.</li>
Move it to 2.1.1 Keyboard (Level A) item. And replace description on 'Group footer summary and total summary are not supported'

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>FilterRow may lose the <code>aria-describedby</code> attribute.</li>
it is not reproduced

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Current page size and index.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Current page size and index.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>HeaderFilter icons do not have <code>alt</code> attributes.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Filter icons in the filter row do not have aria-label attributes.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Summaries are not pronounced.</li>
TreeList is not support the summary

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>FilterRow may lose the <code>aria-describedby</code> attribute.</li>
it is not reproduced

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Keyboard navigation does not work properly in <code>repaintChangesOnly</code> mode.</li>
It is not reproduced

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Keyboard navigation does not work properly in <code>repaintChangesOnly</code> mode.</li>
It is not reproduced

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The column fixing and column visibility customization features cause accessibility issues.</li>
Issue with column fixing is described already. Leave only description about Column chooser in 'drag' mode.

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The column fixing and column visibility customization features cause accessibility issues.</li>
Issue with column fixing is described already. Leave only description about Column chooser in 'drag' mode.

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Users cannot export data.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Users cannot export data.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +            <li>Users must use the 'Shift+Tab' shortcut to move focus from the Column Chooser in DataGrid.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +            <li>Users must use the 'Shift+Tab' shortcut to move focus from the Column Chooser in TreeList.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +            <li>The column fixing feature in TreeList might cause a keyboard trap.</li>
It is not reproduced

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +        </ul></td>
Keyboard trap appears when there is a group footer summary

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +            <li>The column fixing feature in DataGrid might cause a keyboard trap.</li>
It is not reproduced

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +        <td>Adaptive rows cannot be expanded/collapsed using keyboard navigation.</td>
Move it to '2.1.1 Keyboard (Level A)' item

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +        <td>Adaptive rows cannot be expanded/collapsed using keyboard navigation.</td>
Move it to '2.1.1 Keyboard (Level A)' item

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The sorting and export buttons, HeaderFilter, and FilterRow do not supply any instructions.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The sorting and export buttons, HeaderFilter, and FilterRow do not supply any instructions.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The ‘Select All’ checkbox does not supply instructions.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The ‘Select All’ checkbox does not supply instructions.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>TreeView in ColumnChooser and HeaderFilter applies redundant aria-expanded attributes to these elements.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>TreeView in ColumnChooser and HeaderFilter applies redundant aria-expanded attributes to these elements.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Validation frame, sort indexes, and the export button in the toolbar are not accessible.</li>
Issue with export button is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Validation frame, sort indexes, and the export button in the toolbar are not accessible.</li>
Issue with export button is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Validation frame, sort indexes, and the export button in the toolbar are not accessible.</li>
And replace 'indexes' -> 'indices'

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>Validation frame, sort indexes, and the export button in the toolbar are not accessible.</li>
And replace 'indexes' -> 'indices'

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The column fixing feature does not meet this criterion.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The column fixing feature does not meet this criterion.</li>
It is not actual

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
> +        <td>11.5.2.13 Tracking of focus and selection attributes</td>
You can remove all row

2023-05-16 15:08 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +        <td>11.5.2.13 Tracking of focus and selection attributes</td>
You can remove all row

2023-05-17 06:24 UTC, vladaskorohodova commented on concepts/05 UI Components/DataGrid/05 Accessibility/05 Accessibility Features Overview.md
I can't do that, the table with icons is approved by PMs and will be in every accessibility topic

2023-05-17 06:49 UTC, vladaskorohodova commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The column fixing and column visibility customization features cause accessibility issues.</li>
What about ColumnChooser in 'drag' mode? What exactly does not work?

2023-05-17 12:40 UTC, Alyar666 commented on concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
> +                <li>The column fixing and column visibility customization features cause accessibility issues.</li>
> What about ColumnChooser in 'drag' mode? What exactly does not work?

 Keyboard navigation not working for column chooser items

2023-05-17 13:06 UTC, dirk-pieterse approved these changes

2023-05-17 13:06 UTC, dirk-pieterse commented on concepts/05 UI Components/DataGrid/50 Selection/10 User Interaction.md
> +The [showCheckBoxesMode](/api-reference/10%20UI%20Components/dxDataGrid/1%20Configuration/selection/showCheckBoxesMode.md '/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/selection
```suggestion
The [showCheckBoxesMode](/api-reference/10%20UI%20Components/dxDataGrid/1%20Configuration/selection/showCheckBoxesMode.md '/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/selection/#showCheckBoxesMode') the property specifies when the UI component renders checkboxes in the selection column. For example, the following code tells the UI component to never render them, though a user can still select rows using [keyboard shortcuts](/Documentation/Guide/UI_Components/DataGrid/Accessibility/#Keyboard_Navigation):
```

2023-05-17 13:06 UTC, dirk-pieterse commented on concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
> +An end user can use the following keys to interact with the TreeList component:
Can you explain why you change it from "A user" to "An end user"?

```suggestion
A user can use the following keys to interact with the TreeList component: 
```

2023-05-17 13:09 UTC, vladaskorohodova commented on concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
> +An end user can use the following keys to interact with the TreeList component:
I felt like I had to accentuate here that exactly an end user can use keyboard navigation.

2023-05-17 13:23 UTC, dirk-pieterse commented on concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
> +An end user can use the following keys to interact with the TreeList component:
The distinction is between the reader and the user - when we say 'user', it is about the user of the software or application, not the person reading the doc or instructions

2023-05-17 15:32 UTC, Alyar666 approved these changes

2023-05-18 05:56 UTC, vladaskorohodova commented on concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
> +An end user can use the following keys to interact with the TreeList component:
Okay, I will go with 'user' then.

2023-05-18 12:45 UTC, Raushen approved these changes

2023-05-18 12:57 UTC, merged