Enhance the description of the allowReordering option
DevExpress/devextreme-documentation pull request #524
Opened 2020-03-18 11:48 UTC by AlexJameson

2020-03-18 12:32 UTC, RomanTsukanov requested changes

2020-03-18 12:32 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/GridBase/1 Configuration/rowDragging/allowReordering.md
> +This option only enables dragging. You should also implement the reordering logic in the [onReorder]({basewidgetpath}/Configuration/rowDragging/#onReorder) function. If you need to perform cross-comp
It's unclear whether I should implement both these functions if I need reordering _and_ cross-component drag-and-drop or only `onAdd` will do.

2020-03-18 12:32 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/GridBase/1 Configuration/rowDragging/allowReordering.md
> +This option only enables dragging. You should also implement the reordering logic in the [onReorder]({basewidgetpath}/Configuration/rowDragging/#onReorder) function. If you need to perform cross-comp
Both `onReorder` and `onAdd` are functions and handlers, but when you call one of them a "function" and the other a "handler", it seems that they are from different classes.

2020-03-18 14:42 UTC, RomanTsukanov approved these changes

2020-03-19 08:16 UTC, dirk-pieterse approved these changes

2020-03-19 08:16 UTC, merged