Autocomplete: add Vue and React code snippets
DevExpress/devextreme-documentation pull request #659
Opened 2020-04-15 14:41 UTC by ksercs

2020-04-16 09:19 UTC, RomanTsukanov requested changes

2020-04-16 09:19 UTC, RomanTsukanov commented on concepts/05 Widgets/Autocomplete/05 Customize Item Appearance.md
> +If you need a more flexible solution, define a custom template for items of the widget. For Angular apps, DevExtreme provides the [dxTemplate](/api-reference/10%20UI%20Widgets/Markup%20Components/dxT
Same note as [here](https://github.com/DevExpress/devextreme-documentation/pull/658#discussion_r409374999)

2020-04-20 14:24 UTC, ksercs commented on concepts/05 Widgets/Autocomplete/05 Customize Item Appearance.md
> +If you need a more flexible solution, define a custom template for items of the widget. For Angular apps, DevExtreme provides the [dxTemplate](/api-reference/10%20UI%20Widgets/Markup%20Components/dxT
fixed

2020-04-20 14:43 UTC, RomanTsukanov approved these changes

2020-04-22 16:48 UTC, AlexJameson approved these changes

2020-04-23 09:57 UTC, merged