Add React/Vue snippets for Chart Data Aggregation topics
DevExpress/devextreme-documentation pull request #737
Opened 2020-05-08 10:50 UTC by dxBeardedBear

2020-05-12 15:20 UTC, RomanTsukanov requested changes

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/01 Enable Data Aggregation.md
> +            >
```suggestion
                :fullstackedbar="fullStackedBarSettings"> <!-- Enables data aggregation for all Full-Stacked Bar series -->
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/01 Enable Data Aggregation.md
> +                    >
```suggestion
                        fullstackedbar={fullStackedBarSettings}> {/* Enables data aggregation for all Full-Stacked Bar series */}
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/05 Specify the Aggregation Interval.md
> +                >
```suggestion
                    aggregation-interval="day"> <!-- A new interval every day -->
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/05 Specify the Aggregation Interval.md
> +                        >
```suggestion
                            aggregationInterval="day"> {/* A new interval every day */}
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/10 Choose the Aggregation Method.md
> +            >
```suggestion
                type="line">
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/10 Choose the Aggregation Method.md
> +            >
```suggestion
                type="bar">
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/10 Choose the Aggregation Method.md
> +                    >
```suggestion
                        type="line">
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/10 Choose the Aggregation Method.md
> +                    >
```suggestion
                        type="bar">
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/20 Implement a Custom Aggregate Function.md
> +            >
```suggestion
                value-field="value">
```

2020-05-12 15:20 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/88 Data Aggregation/20 Implement a Custom Aggregate Function.md
> +                    >
```suggestion
                        valueField="value">
```

2020-05-13 07:14 UTC, dxBeardedBear commented on concepts/05 Widgets/Chart/88 Data Aggregation/01 Enable Data Aggregation.md
> +            >
Fixed

2020-05-13 13:40 UTC, RomanTsukanov approved these changes

2020-05-13 14:33 UTC, merged