Add React/Vue snippets for Chart/Range Selector zooming and panning topics
DevExpress/devextreme-documentation pull request #738
Opened 2020-05-08 10:50 UTC by dxBeardedBear

2020-05-12 15:23 UTC, RomanTsukanov requested changes

2020-05-12 15:23 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/95 Zooming and Panning/10 Using the RangeSelector Widget.md
> +        >
```suggestion
            :series="seriesConfiguration">
```

2020-05-12 15:23 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/95 Zooming and Panning/10 Using the RangeSelector Widget.md
> +        >
```suggestion
            :value.sync="chart_visualRange">
```

2020-05-12 15:23 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/95 Zooming and Panning/10 Using the RangeSelector Widget.md
> +                >
```suggestion
                    series={seriesConfiguration}>
```

2020-05-12 15:23 UTC, RomanTsukanov commented on concepts/05 Widgets/Chart/95 Zooming and Panning/10 Using the RangeSelector Widget.md
> +                >
```suggestion
                    onValueChanged={this.updateChartVisualRange}>
```

2020-05-13 07:15 UTC, dxBeardedBear commented on concepts/05 Widgets/Chart/95 Zooming and Panning/10 Using the RangeSelector Widget.md
> +        >
Fixed

2020-05-13 13:40 UTC, RomanTsukanov approved these changes

2020-05-13 14:34 UTC, merged