Mention the today button when the applyValueMode is useButtons
DevExpress/devextreme-documentation pull request #76
Opened 2020-01-14 13:58 UTC by AlexJameson

2020-01-14 14:10 UTC, sometimesElen requested changes
We need to add info that the Today button will be displayed if pickerType: "calendar"

2020-01-14 15:03 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDateBox/1 Configuration/applyValueMode.md
> + Enables an end-user to apply the selected value or cancel the selection using the Apply and Cancel buttons respectively. Choosing this mode activates the [showTodayButton](/api-reference/10%20UI%20W
Write button names without quotes and in normal font:

> the Today button

2020-01-15 08:34 UTC, DevExpressSupportTeam approved these changes
LGTM

2020-01-15 08:35 UTC, sometimesElen approved these changes

2020-01-15 08:59 UTC, RomanTsukanov approved these changes

2020-01-16 17:40 UTC, arminal commented on api-reference/10 UI Widgets/dxDateBox/1 Configuration/applyValueMode.md
> + Enables an end-user to apply the selected value or cancel the selection using the Apply and Cancel buttons respectively. When the [pickerType](/api-reference/10%20UI%20Widgets/dxDateBox/1%20Configur
From your writing, it is not clear how the Today button appearing is related to the rest of the sentence. Please rewrite.

2020-01-20 07:43 UTC, merged