Update the workaround in the onExporting option
DevExpress/devextreme-documentation pull request #766
Opened 2020-05-15 12:06 UTC by AlexJameson

2020-05-15 12:29 UTC, RomanTsukanov requested changes

2020-05-15 12:29 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +                    });
Alignments are messed up.

2020-05-15 12:29 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +                        });
The same problem with alignments.

2020-05-15 12:29 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +                    });
And here.

2020-05-15 12:31 UTC, EugeniyKiyashko commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +                workbook.xlsx
In this code example need to fix the indentations. 
Check it also in all approaches, pls

2020-05-15 12:40 UTC, EugeniyKiyashko commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +            e.component.columnOption("ID", "visible", true);
Should we not use the single quotes for js code in snippets?

2020-05-18 10:28 UTC, RomanTsukanov requested changes

2020-05-18 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +            <DxColumn data-field='ID' :visible="false" />
Attributes should use double quotes.

```suggestion
            <DxColumn data-field="ID" :visible="false" />
```

2020-05-18 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +        <dxi-column dataField='ID' [visible]="false"></dxi-column>
```suggestion
        <dxi-column dataField="ID" [visible]="false"></dxi-column>
```

2020-05-18 10:28 UTC, RomanTsukanov commented on api-reference/10 UI Widgets/dxDataGrid/1 Configuration/onExporting.md
> +                    <Column dataField='ID' visible={false} />
```suggestion
                    <Column dataField="ID" visible={false} />
```

2020-05-18 15:58 UTC, RomanTsukanov approved these changes

2020-05-18 18:00 UTC, merged