Fix mentions of the old export in Charts
DevExpress/devextreme-documentation pull request #775
Opened 2020-05-18 16:01 UTC by AlexJameson

2020-05-19 07:49 UTC, dxBeardedBear approved these changes

2020-05-19 07:52 UTC, alexanderPolosatov approved these changes

2020-05-19 13:04 UTC, RomanTsukanov requested changes
Server-side proxy is no longer required. I think we should remove the guides alrogether.

2020-05-21 14:01 UTC, RomanTsukanov approved these changes

2020-05-21 16:13 UTC, merged