Fix the argumentAxis.categories description (T890311)
DevExpress/devextreme-documentation pull request #847
Opened 2020-05-28 14:02 UTC by AlexJameson

2020-05-28 15:42 UTC, pavelgruba approved these changes

2020-05-28 18:35 UTC, pavelgruba approved these changes

2020-05-29 14:44 UTC, RomanTsukanov requested changes

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +Arguments of the `string` type on discrete axes keep the order of objects in the data source. Assign an array of properly sorted arguments to the **categories** option to sort the arguments, for exam
```suggestion
Arguments of the `string` type on discrete axes keep the order of objects in the data source. Assign an array of properly sorted arguments to the **categories** option to sort the arguments as you need, for example, alphabetically: 
```

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +            [argumentField]="continent">
```suggestion
            argumentField="continent">
```

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +    <!--HTML--><dx-chart ...
The proper tab name is missing.

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +                ];
It's an object, it cannot contain semicolons.

```suggestion
                ],
```

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +                continentNames = [
```suggestion
                continentNames: [
```

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +                ];
```suggestion
                ]
```

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +Arguments of the `number` and `date` types on discrete axes are sorted in ascending order regardless of the order they have in the data source. Do not specify the **categories** option for these argu
Is is forbidden to specify `categories` in this case, or are categories simply ignored?

2020-05-29 14:44 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxPolarChart/1 Configuration/argumentAxis/categories.md
> +Arguments of the `string` type on discrete axes keep the order of objects in the data source. Assign an array of properly sorted arguments to the **categories** option to sort the arguments, for exam
I think it is possible to inherit the description from the Chart. Of course, you should use {WidgetName} in the Chart's code in this case.

2020-06-01 06:41 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +Arguments of the `number` and `date` types on discrete axes are sorted in ascending order regardless of the order they have in the data source.
It's now unclear why we mention numeric and date types if `categories` have no impact on them or their use is not recommended.

2020-06-03 21:30 UTC, pavelgruba approved these changes

2020-06-04 09:50 UTC, RomanTsukanov commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +Specify the **categories** array to set the required order of arguments. In the following example, arguments are sorted alphabetically:
Should this sentence be on a new line?

2020-06-04 15:10 UTC, pavelgruba approved these changes

2020-06-04 15:23 UTC, RomanTsukanov approved these changes

2020-06-04 16:31 UTC, albertov05 commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/argumentAxis/categories.md
> +Arguments of the `string` type on discrete axes keep the order of objects in the data source. Arguments of the `number` and `date` types are sorted in ascending order regardless of the order they hav
```suggestion
Arguments of the `string` type on discrete axes maintain the order of objects in the data source. Arguments of the `number` and `date` types are sorted in ascending order regardless of their order within the data source. Specify the **categories** array to set the required order of arguments. In the following example, arguments are sorted alphabetically: 
```

2020-06-04 16:37 UTC, albertov05 commented on api-reference/20 Data Visualization Widgets/dxChart/1 Configuration/valueAxis/categories.md
> +Values of the `string` type on discrete axes keep the order of objects in the data source. Values of the `number` and `date` types are sorted in ascending order regardless of the order they have in t
```suggestion
Values of the `string` type on discrete axes maintain the order of objects in the data source. Values of the `number` and `date` types are sorted in ascending order regardless of their order within the data source. Specify the **categories** array to set the required order of values. In the following example, the values are sorted alphabetically: 
```

2020-06-05 09:23 UTC, merged