ProgressBar: add Angular, Vue and React code snippets
DevExpress/devextreme-documentation pull request #855
Opened 2020-06-01 15:25 UTC by ksercs

2020-06-08 10:22 UTC, AlexJameson approved these changes

2020-06-08 14:14 UTC, RomanTsukanov requested changes

2020-06-08 14:14 UTC, RomanTsukanov commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +                 return value + "USD";
```suggestion
                 return value + " USD";
```

2020-06-08 14:14 UTC, RomanTsukanov commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +            return value + "USD";
```suggestion
            return value + " USD";
```

2020-06-08 14:14 UTC, RomanTsukanov commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +                return value + "USD";
```suggestion
                return value + " USD";
```

2020-06-08 14:14 UTC, RomanTsukanov commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +            return value + "USD";
```suggestion
            return value + " USD";
```

2020-06-09 08:28 UTC, ksercs commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +                 return value + "USD";
fixed

2020-06-09 08:28 UTC, ksercs commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +            return value + "USD";
fixed

2020-06-09 08:28 UTC, ksercs commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +                return value + "USD";
fixed

2020-06-09 08:28 UTC, ksercs commented on concepts/05 Widgets/ProgressBar/05 Progress Status.md
> +            return value + "USD";
fixed

2020-06-09 08:43 UTC, RomanTsukanov approved these changes

2020-06-09 09:13 UTC, merged