Tooltip: add Vue and React code snippets
DevExpress/devextreme-documentation pull request #879
Opened 2020-06-05 17:50 UTC by ksercs

2020-06-05 17:51 UTC, ksercs commented
There is "devextreme-documentation\concepts\05 Widgets\Tooltip\10 Customize the Content\Customize the Content.md" empty file. Should we remove it?

2020-06-05 17:55 UTC, ksercs commented
Tooltip target image is unavailable now. Should we change the image source to real and add it to the markup in Vue and React code snippets?

2020-06-09 11:26 UTC, AlexJameson approved these changes

2020-06-09 11:26 UTC, AlexJameson commented on concepts/05 Widgets/Tooltip/10 Customize the Content/5 Switching Templates On the Fly.md
> +                this.currentTemplate = (this.currentTemplate === 'template1' ? 'template2' : 'template1')
```suggestion
                this.currentTemplate = (this.currentTemplate === 'template1' ? 'template2' : 'template1');
```

2020-06-09 11:26 UTC, AlexJameson commented
> 
> 
> Tooltip target image is unavailable now. Should we change the image source to real and add it to the markup in Vue and React code snippets?

I don't think so.

2020-06-09 11:27 UTC, AlexJameson commented
> 
> 
> There is "_devextreme-documentation\concepts\05 Widgets\Tooltip\10 Customize the Content\Customize the Content.md_" empty file. Should we remove it?

We should keep it for some menu rendering related issues.

2020-06-09 11:33 UTC, ksercs commented on concepts/05 Widgets/Tooltip/10 Customize the Content/5 Switching Templates On the Fly.md
> +                this.currentTemplate = (this.currentTemplate === 'template1' ? 'template2' : 'template1')
fixed

2020-06-09 15:55 UTC, RomanTsukanov requested changes

2020-06-09 15:55 UTC, RomanTsukanov commented on concepts/05 Widgets/Tooltip/00 Overview.md
> +            <img id="image" src="https://www.devexpress.com/DXR.axd?r=9999_17-FD0Id" />
```suggestion
            <img id="image" src="https://url/to/an/image" />
```

2020-06-09 15:55 UTC, RomanTsukanov commented on concepts/05 Widgets/Tooltip/05 Show and Hide the Tooltip/05 API.md
> +With Angular, Vue, or React, use a different technique. Bind the [visible](/api-reference/10%20UI%20Widgets/dxOverlay/1%20Configuration/visible.md '/Documentation/ApiReference/UI_Widgets/dxTooltip/Co
```suggestion
With Angular, Vue, or React, use a different technique. Bind the [visible](/api-reference/10%20UI%20Widgets/dxOverlay/1%20Configuration/visible.md '/Documentation/ApiReference/UI_Widgets/dxTooltip/Configuration/#visible') property of the **Tooltip** widget to a component property. After that, change this component property, and the **Tooltip** will appear or disappear.
```

2020-06-09 18:52 UTC, ksercs commented on concepts/05 Widgets/Tooltip/05 Show and Hide the Tooltip/05 API.md
> +With Angular, Vue, or React, use a different technique. Bind the [visible](/api-reference/10%20UI%20Widgets/dxOverlay/1%20Configuration/visible.md '/Documentation/ApiReference/UI_Widgets/dxTooltip/Co
fixed

2020-06-09 18:58 UTC, ksercs commented on concepts/05 Widgets/Tooltip/00 Overview.md
> +            <img id="image" src="https://www.devexpress.com/DXR.axd?r=9999_17-FD0Id" />
fixed

2020-06-10 10:30 UTC, RomanTsukanov approved these changes

2020-06-10 11:41 UTC, merged