Popup: add Vue and React code snippets
DevExpress/devextreme-documentation pull request #890
Opened 2020-06-08 06:11 UTC by ksercs

2020-06-08 06:13 UTC, ksercs commented
There is `_F:\devextreme-documentation\concepts\05 Widgets\Tooltip\10 Customize the Content\Customize the Content.md_` empty file. Should we remove it or add some tags?

2020-06-09 16:02 UTC, RomanTsukanov requested changes

2020-06-09 16:02 UTC, RomanTsukanov commented on concepts/05 Widgets/Popup/05 Customize the Appearance/10 Customize the Title.md
> +                    showTitle={false}
onHiding is missing.

2020-06-09 16:02 UTC, RomanTsukanov commented on concepts/05 Widgets/Popup/05 Customize the Appearance/20 Specify Toolbar Items.md
> +                >
```suggestion
                    onHiding={this.onHiding}>
```

2020-06-09 16:02 UTC, RomanTsukanov commented on concepts/05 Widgets/Popup/10 Show and Hide the Popup/01 API.md
> +With Angular, Vue or React, use a different technique. Bind the [visible](/api-reference/10%20UI%20Widgets/dxOverlay/1%20Configuration/visible.md '/Documentation/ApiReference/UI_Widgets/dxPopup/Confi
```suggestion
With Angular, Vue or React, use a different technique. Bind the [visible](/api-reference/10%20UI%20Widgets/dxOverlay/1%20Configuration/visible.md '/Documentation/ApiReference/UI_Widgets/dxPopup/Configuration/#visible') property of the **Popup** widget to a component property. After that, change this component property, and the **Popup** will appear or disappear.
```

2020-06-09 19:00 UTC, ksercs commented on concepts/05 Widgets/Popup/05 Customize the Appearance/10 Customize the Title.md
> +                    showTitle={false}
fixed

2020-06-09 19:01 UTC, ksercs commented on concepts/05 Widgets/Popup/05 Customize the Appearance/20 Specify Toolbar Items.md
> +                >
fixed

2020-06-09 19:02 UTC, ksercs commented on concepts/05 Widgets/Popup/10 Show and Hide the Popup/01 API.md
> +With Angular, Vue or React, use a different technique. Bind the [visible](/api-reference/10%20UI%20Widgets/dxOverlay/1%20Configuration/visible.md '/Documentation/ApiReference/UI_Widgets/dxPopup/Confi
fixed

2020-06-10 10:43 UTC, RomanTsukanov approved these changes

2020-06-10 10:56 UTC, AlexJameson approved these changes

2020-06-10 11:49 UTC, merged